--*************************************--
-- Trajet par TomLaVachette
-- Piou Astrub aléatoire
-- SwiftBot.fr
--_____________________________________--

MIN_MONSTERS = 1
MAX_MONSTERS = 8

function npctoastrub()
	npc:npc(2889,3)
	npc:reply(-1)
	npc:reply(-1)
	npc:leaveDialog()
end

function move()
	return {
		{ map = "83887104", path = "396" }, -- Incarnam -> Astrub
		{ map = "153092354", door = "409" },
		{ map = "152045571", path = "right" },
		{ map = "152043521", path = "right" },
		{ map = "-2,-3", path = "right" },
		{ map = "-1,-3", path = "right" },
		{ map = "0,-3", path = "right" },
		{ map = "1,-3", path = "right" },
		{ map = "2,-3", path = "right" },
		{ map = "3,-3", path = "right" },
		{ map = "4,-3", custom = npctoastrub },
		{ map = "84674566", path = "top" },
		
		{ map = "2,-12", path = "right" },
		{ map = "3,-12", path = "right" },
		{ map = "4,-12", path = "top" },
		{ map = "4,-13", path = "top" },
		{ map = "4,-14", path = "top(9)" },
		
		{ map = "0,-22", fight = true, path = "right|bottom" },
		{ map = "1,-22", fight = true, path = "left|right|bottom" },
		{ map = "2,-22", fight = true, path = "left|right|bottom" },
		{ map = "3,-22", fight = true, path = "left(336)|right(251)|bottom(557)" },
		{ map = "4,-22", fight = true, path = "left|right|bottom" },
		{ map = "5,-22", fight = true, path = "left|bottom" },
		{ map = "-1,-21", fight = true, path = "right|bottom" },
		{ map = "0,-21", fight = true, path = "top|left|right|bottom" },
		{ map = "1,-21", fight = true, path = "top|left|right|bottom" },
		{ map = "3,-20", fight = true, path = "top|left|right|bottom" },
		{ map = "2,-21", fight = true, path = "top|left|right|bottom" },
		{ map = "3,-21", fight = true, path = "top|left|right|bottom" },
		{ map = "4,-21", fight = true, path = "top|left|right|bottom" },
		{ map = "5,-21", fight = true, path = "top|left|right|bottom" },
		{ map = "6,-21", fight = true, path = "left|bottom" },
		{ map = "7,-21", fight = true, path = "left(448)|bottom(549)" },
		{ map = "-1,-20", fight = true, path = "top|right|bottom" },
		{ map = "0,-20", fight = true, path = "top|left|right|bottom" },
		{ map = "1,-20", fight = true, path = "top|left|right|bottom" },
		{ map = "2,-20", fight = true, path = "top|left|right|bottom" },
		{ map = "4,-20", fight = true, path = "top|left|right|bottom" },
		{ map = "5,-20", fight = true, path = "top|left|right|bottom" },
		{ map = "6,-20", fight = true, path = "top|left|right|bottom" },
		{ map = "7,-20", fight = true, path = "top|left|bottom" },
		{ map = "-1,-19", fight = true, path = "top|right|bottom" },
		{ map = "0,-19", fight = true, path = "top|left|right|bottom" },
		{ map = "1,-19", fight = true, path = "top|left|right|bottom" },
		{ map = "2,-19", fight = true, path = "top|left|right|bottom" },
		{ map = "3,-19", fight = true, path = "top|left|right|bottom" },
		{ map = "4,-19", fight = true, path = "top|left|right|bottom" },
		{ map = "5,-19", fight = true, path = "top|left|right|bottom" },
		{ map = "6,-19", fight = true, path = "top|left|right|bottom" },
		{ map = "7,-19", fight = true, path = "top|left|bottom" },
		{ map = "-1,-18", fight = true, path = "top|right|bottom" },
		{ map = "0,-18", fight = true, path = "top|left|right|bottom" },
		{ map = "1,-18", fight = true, path = "top|left|right" },
		{ map = "2,-18", fight = true, path = "top|left|right|bottom" },
		{ map = "3,-18", fight = true, path = "top|left|right|bottom" },
		{ map = "4,-18", fight = true, path = "top|left|right|bottom" },
		{ map = "5,-18", fight = true, path = "top|left|right|bottom" },
		{ map = "6,-18", fight = true, path = "top|left|right|bottom" },
		{ map = "7,-18", fight = true, path = "top|left|bottom" },
		{ map = "-1,-17", fight = true, path = "top|right|bottom" },
		{ map = "0,-17", fight = true, path = "top|left|right|bottom" },
		{ map = "1,-17", fight = true, path = "left|right|bottom" },
		{ map = "2,-17", fight = true, path = "top|left|right|bottom" },
		{ map = "3,-17", fight = true, path = "top|left|right|bottom" },
		{ map = "4,-17", fight = true, path = "top|left|right|bottom" },
		{ map = "5,-17", fight = true, path = "top|left|right|bottom" },
		{ map = "6,-17", fight = true, path = "top|left|right|bottom" },
		{ map = "7,-17", fight = true, path = "top|left|bottom" },
		{ map = "-1,-16", fight = true, path = "top|right|bottom" },
		{ map = "0,-16", fight = true, path = "top|left|right|bottom" },
		{ map = "1,-16", fight = true, path = "top|left|right|bottom" },
		{ map = "2,-16", fight = true, path = "top|left|right|bottom" },
		{ map = "3,-16", fight = true, path = "top|left|right|bottom" },
		{ map = "5,-16", fight = true, path = "top|left|right|bottom" },
		{ map = "6,-16", fight = true, path = "top|left|right|bottom" },
		{ map = "7,-16", fight = true, path = "top(6)|left|bottom(551)" },
		{ map = "-1,-15", fight = true, path = "top|right|bottom" },
		{ map = "0,-15", fight = true, path = "top|left|right|bottom" },
		{ map = "1,-15", fight = true, path = "top|left|right|bottom" },
		{ map = "2,-15", fight = true, path = "top|left|right|bottom" },
		{ map = "3,-15", fight = true, path = "top|left|right|bottom" },
		{ map = "4,-15", fight = true, path = "top|left|right(139)" },
		{ map = "5,-15", fight = true, path = "top|left(140)|right(111)" },
		{ map = "4,-16", fight = true, path = "top|left|right|bottom" },
		{ map = "6,-15", fight = true, path = "top|left(140)|right" },
		{ map = "7,-15", fight = true, path = "top|left" },
		{ map = "-1,-14", fight = true, path = "top" },
		{ map = "0,-14", fight = true, path = "top|left|right" },
		{ map = "1,-14", fight = true, path = "top|left|right" },
		{ map = "2,-14", fight = true, path = "top|left|right" },
		{ map = "3,-14", fight = true, path = "top|left" },
	}
end

function bank()
	return {
		{ map="3,-16", path = "right" },
		{ map="2,-16", path = "right" },
		{ map="1,-16", path = "right" },
		{ map="0,-16", path = "right" },
		{ map="-1,-16", path = "right" },
		{ map="-1,-17", path = "right" },
		{ map="0,-17", path = "right" },
		{ map="1,-17", path = "right" },
		{ map="2,-17", path = "right" },
		{ map="3,-17", path = "right" },
		{ map="3,-18", path = "right" },
		{ map="2,-18", path = "right" },
		{ map="1,-18", path = "right" },
		{ map="0,-18", path = "right" },
		{ map="-1,-18", path = "right" },
		{ map="-1,-19", path = "right" },
		{ map="0,-19", path = "right" },
		{ map="1,-19", path = "right" },
		{ map="2,-19", path = "right" },
		{ map="3,-19", path = "right" },
		{ map="3,-20", path = "right" },
		{ map="2,-20", path = "right" },
		{ map="1,-20", path = "right" },
		{ map="0,-20", path = "right" },
		{ map="-1,-20", path = "right" },
		{ map="-1,-21", path = "right" },
		{ map="0,-21", path = "right" },
		{ map="1,-21", path = "right" },
		{ map="2,-21", path = "right" },
		{ map="3,-21", path = "right" },
		{ map="3,-22", path = "right" },
		{ map="2,-22", path = "right" },
		{ map="1,-22", path = "right" },
		{ map="0,-22", path = "right" },
		{ map="5,-22", path = "left" },
		{ map="5,-21", path = "left" },
		{ map="5,-19", path = "left" },
		{ map="5,-18", path = "left" },
		{ map="5,-17", path = "left" },
		{ map="5,-16", path = "left" },
		{ map="5,-15", path = "left" },
		{ map="6,-16", path = "left" },
		{ map="6,-17", path = "left" },
		{ map="6,-18", path = "left" },
		{ map="6,-19", path = "left" },
		{ map="6,-21", path = "left" },
		{ map="5,-20", path = "left" },
		{ map="6,-20", path = "left" },
		{ map="7,-20", path = "left" },
		{ map="7,-21", path = "left" },
		{ map="7,-19", path = "left" },
		{ map="7,-18", path = "left" },
		{ map="7,-17", path = "left" },
		{ map="7,-16", path = "left" },
		{ map="7,-15", path = "left" },
		{ map="6,-15", path = "left" },
		{ map="3,-15", path = "right" },
		{ map="2,-15", path = "right" },
		{ map="1,-15", path = "right" },
		{ map="0,-15", path = "right" },
		{ map="-1,-15", path = "right" },
		{ map="-1,-14", path = "top" },
		{ map="0,-14", path = "top" },
		{ map="1,-14", path = "top" },
		{ map="2,-14", path = "top" },
		{ map="3,-14", path = "top" },
		{ map="4,-15", path = "top" },
		{ map="4,-17", path = "bottom" },
		{ map="4,-18", path = "bottom" },
		{ map="4,-19", path = "bottom" },
		{ map="4,-20", path = "bottom" },
		{ map="4,-21", path = "bottom" },
		{ map="4,-22", path = "bottom" },
		{ map = "84674566", door = "303" },
		{ map = "83887104", npcBank = true, path = "396" },
	}
end