--*************************************--
-- Trajet par TomLaVachette
-- Bûcheron ♦ niv. 1 à 200
-- SwiftBot.fr
--_____________________________________--

GATHER = { 1, 33, 34, 8, 98, 31, 101, 28, 108, 35, 259, 29, 121, 32, 109, 30, 110, 133 }
AUTO_DELETE = { 303, 473, 476, 460, 2358, 471, 2357, 461, 7013, 474, 16488, 449, 7925, 472, 7016, 470, 7014, 11107 }
OPEN_BAGS = true

MyZaap = 0
msgetape1 = false
msgetape2 = false
msgetape3 = false
msgetape4 = false
msgetape5 = false

function move()
	if job:level(2) < 20 then
		return Etape1()
	elseif job:level(2) > 19 and job:level(2) < 40 then
		return Etape2()
	elseif job:level(2) > 39 and job:level(2) < 60 then
		return Etape3()
	elseif job:level(2) > 59 and job:level(2) < 70 then
		return Etape4()
	elseif job:level(2) > 69 and job:level(2) < 90 then
		return Etape5()
	elseif job:level(2) > 89 and job:level(2) < 110 then
		return Etape6()
	elseif job:level(2) > 109 and job:level(2) < 170 then
		return Etape7()
	elseif job:level(2) > 169 and job:level(2) < 200 then
		return Etape8()
	end
end

function Etape1()
	if msgetape1 == false then
		global:printMessage("Étape 1/8 ! Direction Coin des bouftous pour récolter du Bois de Frêne. (1 à 19)")
		msgetape1 = true
	end
	return {
		{ map="0,8", gather = true, path = "bottom" },
		{ map="0,9", gather = true, path = "right" },
		{ map="1,9", gather = true, path = "right" },
		{ map="2,9", gather = true, path = "right" },
		{ map="3,9", gather = true, path = "right" },
		{ map="4,9", gather = true, path = "right" },
		{ map="5,8", gather = true, path = "top" },
		{ map="5,7", gather = true, path = "left", custom = zaap1 },
		{ map="4,7", gather = true, path = "bottom" },
		{ map="3,8", gather = true, path = "left" },
		{ map="2,8", gather = true, path = "left" },
		{ map="1,8", gather = true, path = "left" },
		{ map="5,9", path = "top" },
		{ map="4,8", path = "left" },
		{ map="4,-19", path = "bottom" },
		{ map="4,-18", path = "bottom" },
		{ map="4,-17", path = "bottom" },
		{ map="4,-16", path = "bottom" },
		{ map="4,-15", path = "bottom" },
		{ map="4,-14", path = "bottom" },
		{ map="4,-13", path = "bottom" },
		{ map="4,-12", path = "bottom" },
		{ map="4,-11", path = "bottom" },
		{ map="4,-10", path = "bottom" },
		{ map="4,-9", path = "bottom(558)" },
		{ map="4,-8", path = "bottom" },
		{ map="4,-7", path = "bottom" },
		{ map="4,-6", path = "bottom" },
		{ map="4,-5", path = "bottom" },
		{ map="4,-4", path = "bottom" },
		{ map="4,-3", path = "left" },
		{ map="3,-3", path = "bottom" },
		{ map="3,-2", path = "bottom" },
		{ map="3,-1", path = "bottom" },
		{ map="3,0", path = "right" },
		{ map="4,0", path = "right" },
		{ map="5,0", path = "bottom" },
		{ map="5,1", path = "bottom" },
		{ map="5,2", path = "bottom" },
		{ map="5,3", path = "bottom" },
		{ map="5,4", path = "bottom" },
		{ map="5,5", path = "bottom" },
		{ map="5,6", path = "bottom" },
		{ map="-1,-14", path = "top" },
		{ map="-1,-15", path = "top" },
		{ map="-1,-16", path = "top" },
		{ map="-1,-17", path = "right" },
		{ map="0,-17", path = "right" },
		{ map="1,-17", path = "right" },
		{ map="2,-17", path = "right" },
		{ map="3,-17", path = "right" },
		{ map="3,-16", path = "right" },
		{ map="2,-16", path = "right" },
		{ map="1,-16", path = "right" },
		{ map="0,-16", path = "right" },
		{ map="5,-16", path = "left" },
		{ map="6,-16", path = "left" },
		{ map="5,-17", path = "left" },
		{ map="6,-17", path = "left" },
		{ map="7,-17", path = "left" },
		{ map="7,-15", path = "top" },
		{ map="7,-16", path = "left" },
		{ map="5,-19", path = "left" },
		{ map="6,-20", path = "left" },
		{ map="5,-20", path = "left" },
		{ map="5,-21", path = "left" },
		{ map="6,-21", path = "left" },
		{ map="7,-21", path = "left" },
		{ map="3,-22", path = "right" },
		{ map="2,-22", path = "right" },
		{ map="2,-20", path = "right" },
		{ map="3,-20", path = "right" },
		{ map="3,-19", path = "right" },
		{ map="0,-19", path = "right" },
		{ map="1,-19", path = "right" },
		{ map="2,-19", path = "right" },
		{ map="4,-20", path = "bottom" },
		{ map="4,-21", path = "bottom" },
		{ map="4,-22", path = "bottom" },
	}
end

function Etape2()
	if msgetape2 == false then
		global:printMessage("Étape 2/8 ! Direction Forêt d'Astrub pour récolter du Bois de Châtaignier. (20 à 39)")
		msgetape2 = true
	end
	return {
		{ map="0,8", gather = true, path = "bottom" },
		{ map="0,9", gather = true, path = "right" },
		{ map="1,9", gather = true, path = "right" },
		{ map="2,9", gather = true, path = "right" },
		{ map="3,9", gather = true, path = "right" },
		{ map="4,9", gather = true, path = "right" },
		{ map="5,8", gather = true, path = "top" },
		{ map="5,7", gather = true, path = "top" },
		{ map="4,7", gather = true, path = "bottom" },
		{ map="3,8", gather = true, path = "left" },
		{ map="2,8", gather = true, path = "left" },
		{ map="1,8", gather = true, path = "left" },
		{ map="5,9", path = "top" },
		{ map="4,8", path = "left" },
		{ map="4,-19", path = "top", custom = zaap2 },
		{ map="4,-18", path = "top" },
		{ map="4,-17", path = "top" },
		{ map="4,-16", path = "top" },
		{ map="4,-15", path = "top" },
		{ map="4,-14", path = "top" },
		{ map="4,-13", path = "top" },
		{ map="4,-12", path = "top" },
		{ map="4,-11", path = "top" },
		{ map="4,-10", path = "top" },
		{ map="4,-9", path = "top" },
		{ map="4,-8", path = "left" },
		{ map="4,-7", path = "top" },
		{ map="4,-6", path = "top" },
		{ map="4,-5", path = "top" },
		{ map="4,-4", path = "top" },
		{ map="4,-3", path = "top" },
		{ map="3,-3", path = "right" },
		{ map="3,-2", path = "top" },
		{ map="3,-1", path = "top" },
		{ map="3,0", path = "top" },
		{ map="4,0", path = "left" },
		{ map="5,0", path = "left" },
		{ map="5,1", path = "top" },
		{ map="5,2", path = "top" },
		{ map="5,3", path = "top" },
		{ map="5,4", path = "top" },
		{ map="5,5", path = "top" },
		{ map="5,6", path = "top" },
		{ map="-1,-14", path = "top" },
		{ map="-1,-15", path = "top" },
		{ map="-1,-16", path = "top" },
		{ map="-1,-17", path = "right" },
		{ map="0,-17", path = "right" },
		{ map="1,-17", path = "right" },
		{ map="2,-17", path = "right" },
		{ map="3,-17", path = "right" },
		{ map="3,-16", path = "right" },
		{ map="2,-16", path = "right" },
		{ map="1,-16", path = "right" },
		{ map="0,-16", path = "right" },
		{ map="5,-16", path = "left" },
		{ map="6,-16", path = "left" },
		{ map="5,-17", path = "left" },
		{ map="6,-17", path = "left" },
		{ map="7,-17", path = "left" },
		{ map="7,-15", path = "top" },
		{ map="7,-16", path = "left" },
		{ map="5,-19", path = "left" },
		{ map="6,-20", path = "left" },
		{ map="5,-20", path = "left" },
		{ map="5,-21", path = "left" },
		{ map="6,-21", path = "left" },
		{ map="7,-21", path = "left" },
		{ map="3,-22", path = "right" },
		{ map="2,-22", path = "right" },
		{ map="2,-20", path = "right" },
		{ map="3,-20", path = "right" },
		{ map="3,-19", path = "right" },
		{ map="0,-19", path = "right" },
		{ map="1,-19", path = "right" },
		{ map="2,-19", path = "right" },
		{ map="4,-20", path = "top" },
		{ map="4,-21", path = "top" },
		{ map="4,-22", path = "right" },
		{ map="-2,-24", gather = true, path = "top" },
		{ map="-2,-25", gather = true, path = "top" },
		{ map="-2,-26", gather = true, path = "top" },
		{ map="-2,-27", gather = true, path = "top" },
		{ map="-2,-28", gather = true, path = "right" },
		{ map="-1,-28", gather = true, path = "right" },
		{ map="0,-28", gather = true, path = "bottom" },
		{ map="-1,-27", gather = true, path = "right" },
		{ map="0,-27", gather = true, path = "right" },
		{ map="1,-27", gather = true, path = "bottom" },
		{ map="1,-26", gather = true, path = "bottom" },
		{ map="1,-25", gather = true, path = "left" },
		{ map="0,-25", gather = true, path = "top" },
		{ map="0,-26", gather = true, path = "left" },
		{ map="-1,-26", gather = true, path = "bottom" },
		{ map="-1,-25", gather = true, path = "bottom" },
		{ map="-1,-24", gather = true, path = "left" },
		{ map="5,-22", path = "top" },
		{ map="5,-23", path = "left" },
		{ map="3,-23", path = "left" },
		{ map="4,-23", path = "left" },
		{ map="2,-23", path = "left" },
		{ map="1,-23", path = "left" },
		{ map="0,-23", path = "left" },
		{ map="-1,-23", path = "top" },
	}
end

function Etape3()
	if msgetape3 == false then
		global:printMessage("Étape 3/8 ! Direction Route de la Côte pour récolter du Bois de Noyer. (40 à 59)")
		msgetape3 = true
	end
	return {
		{ map="-2,-24", gather = true, path = "bottom" },
		{ map="-2,-25", gather = true, path = "top" },
		{ map="-2,-26", gather = true, path = "top" },
		{ map="-2,-27", gather = true, path = "top" },
		{ map="-2,-28", gather = true, path = "right" },
		{ map="-1,-28", gather = true, path = "right" },
		{ map="0,-28", gather = true, path = "bottom" },
		{ map="-2,-28", gather = true, path = "right" },
		{ map="-1,-28", gather = true, path = "right" },
		{ map="0,-28", gather = true, path = "bottom" },
		{ map="-1,-27", gather = true, path = "right" },
		{ map="0,-27", gather = true, path = "right" },
		{ map="1,-27", gather = true, path = "bottom" },
		{ map="1,-26", gather = true, path = "bottom" },
		{ map="1,-25", gather = true, path = "left" },
		{ map="0,-25", gather = true, path = "top" },
		{ map="0,-26", gather = true, path = "left" },
		{ map="-1,-26", gather = true, path = "bottom" },
		{ map="-1,-25", gather = true, path = "bottom" },
		{ map="-1,-24", gather = true, path = "left" },
		{ map="4,-19", path = "top" },
		{ map="4,-20", path = "left" },
		{ map="3,-20", path = "left" },
		{ map="2,-20", path = "left" },
		{ map="1,-20", path = "left" },
		{ map="0,-20", path = "left" },
		{ map="-1,-20", path = "left" },
		{ map="-2,-23", path = "bottom" },
		{ map="-2,-22", path = "bottom" },
		{ map="-2,-21", path = "bottom" },
		{ map="-2,-20", path = "left" },
		{ map="-3,-20", path = "left" },
		{ map="-4,-20", path = "left" },
		{ map="-5,-20", path = "left" },
		{ map="-6,-20", path = "left" },
		{ map="-7,-20", path = "left" },
		{ map="-8,-20", path = "left" },
		{ map="-9,-20", path = "left" },
		{ map="-10,-20", path = "left" },
		{ map="-11,-20", path = "left" },
		{ map="-12,-20", path = "left" },
		{ map="-13,-20", path = "left" },
		{ map="-14,-20", path = "left" },
		{ map="-15,-20", path = "left" },
		{ map="-16,-20", path = "left" },
		{ map="-17,-20", path = "left" },
		{ map="-18,-20", path = "left" },
		{ map="-19,-20", path = "left" },
		{ map="-20,-20", path = "bottom", custom = zaap3 },
		{ map="-20,-19", path = "bottom" },
		{ map="-20,-18", path = "bottom" },
		{ map="-20,-17", path = "bottom" },
		{ map="-21,-16", gather = true, path = "bottom" },
		{ map="-21,-15", gather = true, path = "left" },
		{ map="-22,-15", gather = true, path = "left" },
		{ map="-20,-16", path = "left" },
		{ map="-23,-15", gather = true, path = "bottom" },
		{ map="-24,-16", gather = true, path = "left" },
		{ map="-25,-16", gather = true, path = "top" },
		{ map="-25,-17", gather = true, path = "left" },
		{ map="-26,-17", gather = true, path = "left(140)" },
		{ map="-26,-16", gather = true, path = "left" },
		{ map="-26,-15", gather = true, path = "right" },
		{ map="-25,-15", gather = true, path = "right" },
		{ map="-26,-14", gather = true, path = "top" },
		{ map="-27,-14", gather = true, path = "right" },
		{ map="-28,-14", gather = true, path = "right" },
		{ map="-28,-13", gather = true, path = "top" },
		{ map="-28,-12", gather = true, path = "top" },
		{ map="-27,-12", gather = true, path = "left" },
		{ map="-26,-12", gather = true, path = "left" },
		{ map="-25,-12", gather = true, path = "left" },
		{ map="-24,-12", gather = true, path = "left" },
		{ map="-24,-13", gather = true, path = "bottom" },
		{ map="-24,-14", gather = true, path = "bottom" },
		{ map="-27,-17", gather = true, path = "top" },
		{ map="-27,-18", gather = true, path = "left" },
		{ map="-28,-18", gather = true, path = "top" },
		{ map="-28,-19", gather = true, path = "right" },
		{ map="-27,-19", gather = true, path = "top" },
		{ map="-27,-20", gather = true, path = "left" },
		{ map="-28,-20", gather = true, path = "top" },
		{ map="-28,-21", gather = true, path = "left" },
		{ map="-29,-21", gather = true, path = "top" },
		{ map="-29,-23", gather = true, path = "top" },
		{ map="-29,-22", gather = true, path = "top" },
		{ map="-29,-24", gather = true, path = "top" },
		{ map="-29,-27", gather = true, path = "top" },
		{ map="-28,-28", gather = true, path = "right" },
		{ map="-27,-28", gather = true, path = "top" },
		{ map="-27,-29", gather = true, path = "left" },
		{ map="-28,-29", gather = true, path = "top" },
		{ map="-28,-30", gather = true, path = "right" },
		{ map="-27,-30", gather = true, path = "top" },
		{ map="-27,-31", gather = true, path = "top" },
		{ map="-27,-32", gather = true, path = "right" },
		{ map="-26,-32", gather = true, path = "top" },
		{ map="-27,-33", gather = true, path = "top" },
		{ map="-27,-34", gather = true, path = "right" },
		{ map="-26,-34", gather = true, path = "right" },
		{ map="-25,-34", gather = true, path = "top" },
		{ map="-18,-35", gather = true, path = "bottom" },
		{ map="-17,-35", gather = true, path = "left" },
		{ map="-18,-34", gather = true, path = "left" },
		{ map="-19,-34", gather = true, path = "bottom" },
		{ map="-19,-33", gather = true, path = "bottom" },
		{ map="-20,-29", gather = true, path = "bottom" },
		{ map="-20,-28", gather = true, path = "bottom" },
		{ map="-20,-25", gather = true, path = "right" },
		{ map="-19,-25", gather = true, path = "bottom" },
		{ map="-19,-24", gather = true, path = "bottom" },
		{ map="-19,-23", gather = true, path = "bottom" },
		{ map="-22,-21", gather = true, path = "bottom" },
		{ map="-22,-20", gather = true, path = "right" },
		{ map="-21,-20", gather = true, path = "right" },
		{ map="-19,-22", path = "bottom" },
		{ map="-19,-21", path = "left" },
		{ map="-20,-21", path = "left" },
		{ map="-21,-21", path = "left" },
		{ map="-20,-27", path = "bottom" },
		{ map="-20,-26", path = "bottom" },
		{ map="-19,-32", path = "bottom" },
		{ map="-19,-31", path = "bottom" },
		{ map="-19,-30", path = "bottom" },
		{ map="-19,-29", path = "left" },
		{ map="-17,-36", path = "bottom" },
		{ map="-18,-36", path = "right" },
		{ map="-19,-36", path = "right" },
		{ map="-20,-36", path = "right" },
		{ map="-21,-36", path = "right" },
		{ map="-22,-36", path = "right" },
		{ map="-23,-36", path = "right" },
		{ map="-24,-36", path = "right" },
		{ map="-25,-35", path = "top" },
		{ map="-26,-33", path = "left" },
		{ map="-29,-28", path = "right" },
		{ map="-29,-26", path = "top" },
		{ map="-29,-25", path = "top" },
		{ map="-27,-16", path = "top" },
		{ map="-23,-14", path = "left" },
		{ map="-24,-15", path = "top" },
		{ map="-25,-36", path = "right" },
		{ map="-32,-39", path = "right" },
	}
end

function Etape4()
	if msgetape4 == false then
		global:printMessage("Étape 4/8 ! Direction Cania pour récolter du Bois de Chêne. (60 à 69)")
		msgetape4 = true
	end
	return {
		{ map="-20,-20", path = "right", custom = zaap4 },
		{ map="-20,-19", path = "bottom" },
		{ map="-20,-18", path = "bottom" },
		{ map="-21,-16", gather = true, path = "bottom" },
		{ map="-21,-15", gather = true, path = "left" },
		{ map="-22,-15", gather = true, path = "left" },
		{ map="-7,-16", gather = true, path = "bottom" },
		{ map="-20,-16", path = "left" },
		{ map="-23,-15", gather = true, path = "bottom" },
		{ map="-24,-16", gather = true, path = "left" },
		{ map="-25,-16", gather = true, path = "top" },
		{ map="-25,-17", gather = true, path = "left" },
		{ map="-26,-17", gather = true, path = "left(140)" },
		{ map="-26,-16", gather = true, path = "left" },
		{ map="-26,-15", gather = true, path = "right" },
		{ map="-25,-15", gather = true, path = "right" },
		{ map="-26,-14", gather = true, path = "top" },
		{ map="-27,-14", gather = true, path = "right" },
		{ map="-28,-14", gather = true, path = "right" },
		{ map="-28,-13", gather = true, path = "top" },
		{ map="-28,-12", gather = true, path = "top" },
		{ map="-27,-12", gather = true, path = "left" },
		{ map="-26,-12", gather = true, path = "left" },
		{ map="-25,-12", gather = true, path = "left" },
		{ map="-24,-12", gather = true, path = "left" },
		{ map="-24,-13", gather = true, path = "bottom" },
		{ map="-24,-14", gather = true, path = "left" },
		{ map="-27,-17", gather = true, path = "top" },
		{ map="-27,-18", gather = true, path = "left" },
		{ map="-28,-18", gather = true, path = "top" },
		{ map="-28,-19", gather = true, path = "right" },
		{ map="-27,-19", gather = true, path = "top" },
		{ map="-27,-20", gather = true, path = "left" },
		{ map="-28,-20", gather = true, path = "top" },
		{ map="-28,-21", gather = true, path = "left" },
		{ map="-29,-21", gather = true, path = "top" },
		{ map="-29,-23", gather = true, path = "top" },
		{ map="-29,-22", gather = true, path = "top" },
		{ map="-29,-24", gather = true, path = "top" },
		{ map="-29,-27", gather = true, path = "top" },
		{ map="-28,-28", gather = true, path = "right" },
		{ map="-27,-28", gather = true, path = "top" },
		{ map="-27,-29", gather = true, path = "left" },
		{ map="-28,-29", gather = true, path = "top" },
		{ map="-28,-30", gather = true, path = "right" },
		{ map="-27,-30", gather = true, path = "top" },
		{ map="-27,-31", gather = true, path = "top" },
		{ map="-27,-32", gather = true, path = "right" },
		{ map="-26,-32", gather = true, path = "top" },
		{ map="-27,-33", gather = true, path = "top" },
		{ map="-27,-34", gather = true, path = "right" },
		{ map="-26,-34", gather = true, path = "right" },
		{ map="-25,-34", gather = true, path = "top" },
		{ map="-18,-35", gather = true, path = "bottom" },
		{ map="-17,-35", gather = true, path = "left" },
		{ map="-18,-34", gather = true, path = "left" },
		{ map="-19,-34", gather = true, path = "bottom" },
		{ map="-19,-33", gather = true, path = "bottom" },
		{ map="-20,-29", gather = true, path = "bottom" },
		{ map="-20,-28", gather = true, path = "bottom" },
		{ map="-20,-25", gather = true, path = "right" },
		{ map="-19,-25", gather = true, path = "bottom" },
		{ map="-19,-24", gather = true, path = "bottom" },
		{ map="-19,-23", gather = true, path = "bottom" },
		{ map="-22,-21", gather = true, path = "bottom" },
		{ map="-22,-20", gather = true, path = "right" },
		{ map="-21,-20", gather = true, path = "right" },
		{ map="-19,-22", path = "bottom" },
		{ map="-19,-21", path = "left" },
		{ map="-20,-21", path = "left" },
		{ map="-21,-21", path = "left" },
		{ map="-20,-27", path = "bottom" },
		{ map="-20,-26", path = "bottom" },
		{ map="-19,-32", path = "bottom" },
		{ map="-19,-31", path = "bottom" },
		{ map="-19,-30", path = "bottom" },
		{ map="-19,-29", path = "left" },
		{ map="-17,-36", path = "bottom" },
		{ map="-18,-36", path = "right" },
		{ map="-19,-36", path = "right" },
		{ map="-20,-36", path = "right" },
		{ map="-21,-36", path = "right" },
		{ map="-22,-36", path = "right" },
		{ map="-23,-36", path = "right" },
		{ map="-24,-36", path = "right" },
		{ map="-25,-35", path = "top" },
		{ map="-26,-33", path = "left" },
		{ map="-29,-28", path = "right" },
		{ map="-29,-26", path = "top" },
		{ map="-29,-25", path = "top" },
		{ map="-27,-16", path = "top" },
		{ map="-23,-14", path = "left" },
		{ map="-24,-15", path = "top" },
		{ map="-25,-36", path = "right" },
		{ map="-32,-39", path = "right" },
		{ map="-19,-20", gather = true, path = "right" },
		{ map="-19,-19", gather = true, path = "bottom" },
		{ map="-19,-18", gather = true, path = "bottom" },
		{ map="-19,-17", gather = true, path = "left" },
		{ map="-18,-19", gather = true, path = "left" },
		{ map="-18,-18", gather = true, path = "right" },
		{ map="-18,-17", gather = true, path = "top" },
		{ map="-17,-18", gather = true, path = "top" },
		{ map="-17,-17", gather = true, path = "left" },
		{ map="-16,-18", gather = true, path = "right" },
		{ map="-17,-15", gather = true, path = "top" },
		{ map="-17,-16", gather = true, path = "top" },
		{ map="-16,-15", gather = true, path = "left" },
		{ map="-16,-14", gather = true, path = "right" },
		{ map="-15,-15", gather = true, path = "left" },
		{ map="-15,-17", gather = true, path = "right" },
		{ map="-14,-17", gather = true, path = "right" },
		{ map="148111873", door = "233" },
		{ map="147849986", gather = true, path = "right" },
		{ map="-12,-17", gather = true, path = "right" },
		{ map="-15,-13", gather = true, path = "left" },
		{ map="-15,-12", gather = true, path = "top" },
		{ map="-15,-11", gather = true, path = "top" },
		{ map="-14,-11", gather = true, path = "left" },
		{ map="-13,-11", gather = true, path = "left" },
		{ map="-13,-10", gather = true, path = "top" },
		{ map="-11,-9", gather = true, path = "left" },
		{ map="-11,-8", gather = true, path = "top" },
		{ map="-10,-8", gather = true, path = "left" },
		{ map="-10,-9", gather = true, path = "bottom" },
		{ map="-9,-9", gather = true, path = "left" },
		{ map="-9,-8", gather = true, path = "top" },
		{ map="-8,-8", gather = true, path = "left" },
		{ map="-8,-9", gather = true, path = "bottom" },
		{ map="-8,-10", gather = true, path = "bottom" },
		{ map="-8,-12", gather = true, path = "bottom" },
		{ map="-8,-13", gather = true, path = "bottom" },
		{ map="-7,-13", gather = true, path = "left" },
		{ map="-7,-14", gather = true, path = "bottom" },
		{ map="-8,-14", gather = true, path = "right" },
		{ map="-7,-15", gather = true, path = "left" },
		{ map="-8,-16", gather = true, path = "right" },
		{ map="-8,-17", gather = true, path = "bottom" },
		{ map="-9,-17", gather = true, path = "right" },
		{ map="-10,-17", gather = true, path = "right" },
		{ map="-14,-20", gather = true, path = "bottom" },
		{ map="-15,-20", gather = true, path = "right" },
		{ map="-20,-17", gather = true, path = "bottom" },
		{ map="-14,-19", gather = true, path = "left" },
		{ map="-15,-19", gather = true, path = "left" },
		{ map="-16,-19", gather = true, path = "bottom" },
		{ map="-18,-20", path = "right" },
		{ map="-17,-20", path = "right" },
		{ map="-16,-20", gather = true, path = "right" },
		{ map="-15,-18", path = "bottom" },
		{ map="-11,-17", path = "right" },
		{ map="-8,-15", path = "bottom" },
		{ map="-8,-11", path = "bottom" },
		{ map="-12,-9", path = "top" },
		{ map="-12,-10", path = "left" },
		{ map="-16,-13", path = "top" },
		{ map="-15,-14", path = "top" },
		{ map="-17,-19", path = "left" },
		{ map="-25,-13", gather = true, path = "right" },
		{ map="-25,-14", gather = true, path = "bottom" },
		{ map="-8,-19", gather = true, path = "right" },
		{ map="-7,-19", gather = true, path = "top" },
		{ map="-7,-20", gather = true, path = "left" },
		{ map="-8,-20", gather = true, path = "top" },
		{ map="-7,-21", gather = true, path = "top" },
		{ map="-7,-22", gather = true, path = "top" },
		{ map="-7,-23", gather = true, path = "left" },
		{ map="-8,-23", gather = true, path = "top" },
		{ map="-7,-24", gather = true, path = "top" },
		{ map="-7,-25", gather = true, path = "left" },
		{ map="-8,-25", gather = true, path = "top" },
		{ map="-8,-26", gather = true, path = "right" },
		{ map="-7,-26", gather = true, path = "top" },
		{ map="-7,-27", gather = true, path = "top" },
		{ map="-7,-28", gather = true, path = "left" },
		{ map="-8,-28", gather = true, path = "top" },
		{ map="-8,-29", gather = true, path = "right" },
		{ map="-7,-29", gather = true, path = "right" },
		{ map="-6,-30", gather = true, path = "left" },
		{ map="-7,-30", gather = true, path = "left" },
		{ map="-8,-30", gather = true, path = "top" },
		{ map="-8,-31", gather = true, path = "right" },
		{ map="-6,-31", gather = true, path = "top" },
		{ map="-6,-32", gather = true, path = "left" },
		{ map="-7,-32", gather = true, path = "left" },
		{ map="-8,-32", gather = true, path = "top" },
		{ map="-8,-33", gather = true, path = "left" },
		{ map="-9,-33", gather = true, path = "top" },
		{ map="-9,-34", gather = true, path = "left" },
		{ map="-10,-34", gather = true, path = "bottom" },
		{ map="-10,-33", gather = true, path = "left" },
		{ map="-11,-33", gather = true, path = "bottom" },
		{ map="-11,-32", gather = true, path = "bottom" },
		{ map="-11,-31", gather = true, path = "bottom" },
		{ map="-11,-30", gather = true, path = "bottom" },
		{ map="-11,-29", path = "left" },
		{ map="-12,-29", path = "bottom" },
		{ map="-12,-28", path = "left" },
		{ map="-12,-27", path = "bottom" },
		{ map="-12,-26", path = "left" },
		{ map="-13,-26", path = "bottom" },
		{ map="-13,-25", path = "right" },
		{ map="-12,-25", path = "bottom" },
		{ map="-12,-24", path = "bottom" },
		{ map="-12,-23", path = "bottom" },
		{ map="-12,-22", path = "bottom" },
		{ map="-12,-21", path = "bottom" },
		{ map="-12,-20", path = "bottom" },
		{ map="-12,-19", path = "right" },
		{ map="-11,-19", path = "right" },
		{ map="-10,-19", path = "right" },
		{ map="-9,-19", path = "right" },
		{ map="-8,-21", path = "right" },
		{ map="-8,-24", path = "right" },
		{ map="-13,-28", path = "bottom" },
		{ map="-13,-27", path = "right" },
	}
end

function Etape5()
	if msgetape5 == false then
		global:printMessage("Étape 5/8 ! Direction Massif de Cania pour récolter du Bois de Bombu. (70 à 89)")
		msgetape5 = true
	end
	return {
		{ map="-20,-20", path = "right" },
		{ map="-20,-19", path = "bottom" },
		{ map="-20,-18", path = "bottom" },
		{ map="-21,-16", gather = true, path = "bottom" },
		{ map="-21,-15", gather = true, path = "left" },
		{ map="-22,-15", gather = true, path = "left" },
		{ map="-7,-16", gather = true, path = "bottom" },
		{ map="-20,-16", path = "left" },
		{ map="-23,-15", gather = true, path = "bottom" },
		{ map="-24,-16", gather = true, path = "left" },
		{ map="-25,-16", gather = true, path = "top" },
		{ map="-25,-17", gather = true, path = "left" },
		{ map="-26,-17", gather = true, path = "left(140)" },
		{ map="-26,-16", gather = true, path = "left" },
		{ map="-26,-15", gather = true, path = "right" },
		{ map="-25,-15", gather = true, path = "right" },
		{ map="-26,-14", gather = true, path = "top" },
		{ map="-27,-14", gather = true, path = "right" },
		{ map="-28,-14", gather = true, path = "right" },
		{ map="-28,-13", gather = true, path = "top" },
		{ map="-28,-12", gather = true, path = "top" },
		{ map="-27,-12", gather = true, path = "left" },
		{ map="-26,-12", gather = true, path = "left" },
		{ map="-25,-12", gather = true, path = "left" },
		{ map="-24,-12", gather = true, path = "left" },
		{ map="-24,-13", gather = true, path = "bottom" },
		{ map="-24,-14", gather = true, path = "left" },
		{ map="-27,-17", gather = true, path = "top" },
		{ map="-27,-18", gather = true, path = "left" },
		{ map="-28,-18", gather = true, path = "top" },
		{ map="-28,-19", gather = true, path = "right" },
		{ map="-27,-19", gather = true, path = "top" },
		{ map="-27,-20", gather = true, path = "left" },
		{ map="-28,-20", gather = true, path = "top" },
		{ map="-28,-21", gather = true, path = "left" },
		{ map="-29,-21", gather = true, path = "top" },
		{ map="-29,-23", gather = true, path = "top" },
		{ map="-29,-22", gather = true, path = "top" },
		{ map="-29,-24", gather = true, path = "top" },
		{ map="-29,-27", gather = true, path = "top" },
		{ map="-28,-28", gather = true, path = "right" },
		{ map="-27,-28", gather = true, path = "top" },
		{ map="-27,-29", gather = true, path = "left" },
		{ map="-28,-29", gather = true, path = "top" },
		{ map="-28,-30", gather = true, path = "right" },
		{ map="-27,-30", gather = true, path = "top" },
		{ map="-27,-31", gather = true, path = "top" },
		{ map="-27,-32", gather = true, path = "right" },
		{ map="-26,-32", gather = true, path = "top" },
		{ map="-27,-33", gather = true, path = "top" },
		{ map="-27,-34", gather = true, path = "right" },
		{ map="-26,-34", gather = true, path = "right" },
		{ map="-25,-34", gather = true, path = "top" },
		{ map="-18,-35", gather = true, path = "bottom" },
		{ map="-17,-35", gather = true, path = "left" },
		{ map="-18,-34", gather = true, path = "left" },
		{ map="-19,-34", gather = true, path = "bottom" },
		{ map="-19,-33", gather = true, path = "bottom" },
		{ map="-20,-29", gather = true, path = "bottom" },
		{ map="-20,-28", gather = true, path = "bottom" },
		{ map="-20,-25", gather = true, path = "right" },
		{ map="-19,-25", gather = true, path = "bottom" },
		{ map="-19,-24", gather = true, path = "bottom" },
		{ map="-19,-23", gather = true, path = "bottom" },
		{ map="-22,-21", gather = true, path = "bottom" },
		{ map="-22,-20", gather = true, path = "right" },
		{ map="-21,-20", gather = true, path = "right" },
		{ map="-19,-22", path = "bottom" },
		{ map="-19,-21", path = "left" },
		{ map="-20,-21", path = "left" },
		{ map="-21,-21", path = "left" },
		{ map="-20,-27", path = "bottom" },
		{ map="-20,-26", path = "bottom" },
		{ map="-19,-32", path = "bottom" },
		{ map="-19,-31", path = "bottom" },
		{ map="-19,-30", path = "bottom" },
		{ map="-19,-29", path = "left" },
		{ map="-17,-36", path = "bottom" },
		{ map="-18,-36", path = "right" },
		{ map="-19,-36", path = "right" },
		{ map="-20,-36", path = "right" },
		{ map="-21,-36", path = "right" },
		{ map="-22,-36", path = "right" },
		{ map="-23,-36", path = "right" },
		{ map="-24,-36", path = "right" },
		{ map="-25,-35", path = "top" },
		{ map="-26,-33", path = "left" },
		{ map="-29,-28", path = "right" },
		{ map="-29,-26", path = "top" },
		{ map="-29,-25", path = "top" },
		{ map="-27,-16", path = "top" },
		{ map="-23,-14", path = "left" },
		{ map="-24,-15", path = "top" },
		{ map="-25,-36", path = "right" },
		{ map="-32,-39", path = "right" },
		{ map="-19,-20", gather = true, path = "right" },
		{ map="-19,-19", gather = true, path = "bottom" },
		{ map="-19,-18", gather = true, path = "bottom" },
		{ map="-19,-17", gather = true, path = "left" },
		{ map="-18,-19", gather = true, path = "left" },
		{ map="-18,-18", gather = true, path = "right" },
		{ map="-18,-17", gather = true, path = "top" },
		{ map="-17,-18", gather = true, path = "top" },
		{ map="-17,-17", gather = true, path = "left" },
		{ map="-16,-18", gather = true, path = "right" },
		{ map="-17,-15", gather = true, path = "top" },
		{ map="-17,-16", gather = true, path = "top" },
		{ map="-16,-15", gather = true, path = "left" },
		{ map="-16,-14", gather = true, path = "right" },
		{ map="-15,-15", gather = true, path = "left" },
		{ map="-15,-17", gather = true, path = "right" },
		{ map="-14,-17", gather = true, path = "right" },
		{ map="147849986", gather = true, path = "right" },
		{ map="148111873", door = "233" },
		{ map="-12,-17", gather = true, path = "right" },
		{ map="-15,-13", gather = true, path = "left" },
		{ map="-15,-12", gather = true, path = "top" },
		{ map="-15,-11", gather = true, path = "top" },
		{ map="-14,-11", gather = true, path = "left" },
		{ map="-13,-11", gather = true, path = "left" },
		{ map="-13,-10", gather = true, path = "top" },
		{ map="-11,-9", gather = true, path = "left" },
		{ map="-11,-8", gather = true, path = "top" },
		{ map="-10,-8", gather = true, path = "left" },
		{ map="-10,-9", gather = true, path = "bottom" },
		{ map="-9,-9", gather = true, path = "left" },
		{ map="-9,-8", gather = true, path = "top" },
		{ map="-8,-8", gather = true, path = "left" },
		{ map="-8,-9", gather = true, path = "bottom" },
		{ map="-8,-10", gather = true, path = "bottom" },
		{ map="-8,-12", gather = true, path = "bottom" },
		{ map="-8,-13", gather = true, path = "bottom" },
		{ map="-7,-13", gather = true, path = "left" },
		{ map="-7,-14", gather = true, path = "bottom" },
		{ map="-8,-14", gather = true, path = "right" },
		{ map="-7,-15", gather = true, path = "left" },
		{ map="-8,-16", gather = true, path = "right" },
		{ map="-8,-17", gather = true, path = "bottom" },
		{ map="-9,-17", gather = true, path = "right" },
		{ map="-10,-17", gather = true, path = "right" },
		{ map="-14,-20", gather = true, path = "right" },
		{ map="-15,-20", gather = true, path = "right" },
		{ map="-20,-17", gather = true, path = "bottom" },
		{ map="-14,-19", gather = true, path = "left" },
		{ map="-15,-19", gather = true, path = "left" },
		{ map="-16,-19", gather = true, path = "bottom" },
		{ map="-18,-20", path = "right" },
		{ map="-17,-20", path = "right" },
		{ map="-16,-20", gather = true, path = "right" },
		{ map="-15,-18", path = "bottom" },
		{ map="-11,-17", path = "right" },
		{ map="-8,-15", path = "bottom" },
		{ map="-8,-11", path = "bottom" },
		{ map="-12,-9", path = "top" },
		{ map="-12,-10", path = "left" },
		{ map="-16,-13", path = "top" },
		{ map="-15,-14", path = "top" },
		{ map="-17,-19", path = "left" },
		{ map="-25,-13", gather = true, path = "right" },
		{ map="-25,-14", gather = true, path = "bottom" },
		{ map="-8,-19", gather = true, path = "right" },
		{ map="-7,-19", gather = true, path = "top" },
		{ map="-7,-20", gather = true, path = "left" },
		{ map="-8,-20", gather = true, path = "top" },
		{ map="-7,-21", gather = true, path = "top" },
		{ map="-7,-22", gather = true, path = "top" },
		{ map="-7,-23", gather = true, path = "left" },
		{ map="-8,-23", gather = true, path = "top" },
		{ map="-7,-24", gather = true, path = "top" },
		{ map="-7,-25", gather = true, path = "left" },
		{ map="-8,-25", gather = true, path = "top" },
		{ map="-8,-26", gather = true, path = "right" },
		{ map="-7,-26", gather = true, path = "top" },
		{ map="-7,-27", gather = true, path = "top" },
		{ map="-7,-28", gather = true, path = "left" },
		{ map="-8,-28", gather = true, path = "top" },
		{ map="-8,-29", gather = true, path = "right" },
		{ map="-7,-29", gather = true, path = "right" },
		{ map="-6,-30", gather = true, path = "left" },
		{ map="-7,-30", gather = true, path = "left" },
		{ map="-8,-30", gather = true, path = "top" },
		{ map="-8,-31", gather = true, path = "right" },
		{ map="-6,-31", gather = true, path = "top" },
		{ map="-6,-32", gather = true, path = "left" },
		{ map="-7,-32", gather = true, path = "left" },
		{ map="-8,-32", gather = true, path = "top" },
		{ map="-8,-33", gather = true, path = "left" },
		{ map="-9,-33", gather = true, path = "top" },
		{ map="-9,-34", gather = true, path = "left" },
		{ map="-10,-34", gather = true, path = "bottom" },
		{ map="-10,-33", gather = true, path = "left" },
		{ map="-11,-33", gather = true, path = "bottom" },
		{ map="-11,-32", gather = true, path = "bottom" },
		{ map="-11,-31", gather = true, path = "bottom" },
		{ map="-11,-30", gather = true, path = "bottom" },
		{ map="-11,-29", path = "left" },
		{ map="-12,-29", path = "bottom" },
		{ map="-12,-28", path = "left" },
		{ map="-12,-27", path = "bottom" },
		{ map="-12,-26", path = "left" },
		{ map="-13,-26", path = "bottom" },
		{ map="-13,-25", path = "right" },
		{ map="-12,-25", path = "bottom" },
		{ map="-12,-24", path = "bottom" },
		{ map="-12,-23", path = "bottom" },
		{ map="-12,-22", path = "bottom" },
		{ map="-12,-21", path = "bottom" },
		{ map="-12,-20", path = "bottom" },
		{ map="-12,-19", path = "right" },
		{ map="-11,-19", path = "right" },
		{ map="-10,-19", path = "right" },
		{ map="-6,-29", path = "top" },
		{ map="-9,-19", path = "right" },
		{ map="-8,-21", path = "right" },
		{ map="-8,-24", path = "right" },
		{ map="-13,-28", path = "bottom", custom = zaap5 },
		{ map="-13,-27", path = "right" },
		{ map="-13,-20", path = "right" },
		{ map="-7,-31", path = "right" },
	}
end

function Etape6()
	if msgetape6 == false then
		global:printMessage("Étape 6/8 ! Direction Route Sombre pour récolter du Bois d'Oliviolet. (90 à 109)")
		msgetape6 = true
	end
	return {
		{ map="-7,-23", path = "bottom" },
		{ map="-7,-24", path = "bottom" },
		{ map="-8,-24", path = "bottom" },
		{ map="-8,-25", path = "bottom" },
		{ map="-7,-25", path = "bottom" },
		{ map="-7,-26", path = "bottom" },
		{ map="-8,-26", path = "bottom" },
		{ map="-8,-27", path = "bottom" },
		{ map="-7,-27", path = "bottom" },
		{ map="-7,-28", path = "bottom" },
		{ map="-8,-28", path = "bottom" },
		{ map="-8,-29", path = "bottom" },
		{ map="-7,-29", path = "bottom" },
		{ map="-7,-30", path = "bottom" },
		{ map="-8,-30", path = "bottom" },
		{ map="-8,-31", path = "bottom" },
		{ map="-7,-31", path = "bottom" },
		{ map="-6,-30", path = "left" },
		{ map="-6,-31", path = "left" },
		{ map="-6,-32", path = "left" },
		{ map="-7,-32", path = "bottom" },
		{ map="-8,-32", path = "bottom" },
		{ map="-8,-33", path = "bottom" },
		{ map="-9,-33", path = "top" },
		{ map="-9,-34", path = "left" },
		{ map="-10,-34", path = "bottom" },
		{ map="-10,-33", path = "left" },
		{ map="-11,-33", path = "bottom" },
		{ map="-11,-32", path = "bottom" },
		{ map="-11,-31", path = "bottom" },
		{ map="-11,-30", path = "bottom" },
		{ map="-11,-29", path = "left" },
		{ map="-12,-29", path = "bottom" },
		{ map="-12,-28", path = "left" },
		{ map="-13,-28", path = "bottom" },
		{ map="-13,-27", path = "right" },
		{ map="-12,-27", path = "bottom" },
		{ map="-12,-26", path = "left" },
		{ map="-13,-26", path = "bottom" },
		{ map="-13,-25", path = "right" },
		{ map="-12,-25", path = "bottom" },
		{ map="-12,-24", path = "bottom" },
		{ map="-12,-23", path = "bottom" },
		{ map="-12,-22", path = "bottom" },
		{ map="-12,-21", path = "bottom" },
		{ map="-12,-20", path = "left" },
		{ map="-11,-19", path = "left" },
		{ map="-10,-19", path = "left" },
		{ map="-9,-19", path = "left" },
		{ map="-8,-19", path = "left" },
		{ map="-8,-23", path = "bottom" },
		{ map="-8,-21", path = "bottom" },
		{ map="-8,-20", path = "bottom" },
		{ map="-8,-22", path = "bottom" },
		{ map="-7,-22", path = "bottom" },
		{ map="-7,-21", path = "bottom" },
		{ map="-7,-20", path = "bottom" },
		{ map="-7,-19", path = "left" },
		{ map="-12,-19", path = "top" },
		{ map="-13,-20", path = "left" },
		{ map="-14,-20", path = "left" },
		{ map="-15,-20", path = "left" },
		{ map="-16,-20", path = "left" },
		{ map="-17,-20", path = "left" },
		{ map="-18,-20", path = "left" },
		{ map="-19,-20", path = "left" },
		{ map="-20,-20", path = "bottom", custom = zaap6 },
		{ map="-20,-20", path = "bottom" },
		{ map="-20,-19", path = "bottom" },
		{ map="-20,-18", path = "bottom" },
		{ map="-20,-17", path = "bottom" },
		{ map="-20,-16", path = "bottom" },
		{ map="-20,-15", path = "bottom" },
		{ map="-23,-5", gather = true, path = "left" },
		{ map="-22,-5", gather = true, path = "left" },
		{ map="-22,-4", gather = true, path = "top" },
		{ map="-23,-4", gather = true, path = "right" },
		{ map="-23,-3", gather = true, path = "top" },
		{ map="-23,-2", gather = true, path = "left" },
		{ map="-24,-2", gather = true, path = "top" },
		{ map="-24,-3", gather = true, path = "right" },
		{ map="-25,-2", gather = true, path = "bottom" },
		{ map="-25,-4", gather = true, path = "top" },
		{ map="-25,-5", gather = true, path = "left" },
		{ map="-26,-5", gather = true, path = "bottom" },
		{ map="-27,-3", gather = true, path = "bottom" },
		{ map="-27,-2", gather = true, path = "right" },
		{ map="-26,-2", gather = true, path = "right" },
		{ map="-28,-1", gather = true, path = "bottom" },
		{ map="-28,0", gather = true, path = "right" },
		{ map="-27,0", gather = true, path = "right" },
		{ map="-25,-1", gather = true, path = "left" },
		{ map="-25,0", gather = true, path = "bottom" },
		{ map="-24,0", gather = true, path = "top" },
		{ map="-25,1", gather = true, path = "bottom" },
		{ map="-26,2", gather = true, path = "bottom" },
		{ map="-25,2", gather = true, path = "left" },
		{ map="-24,2", gather = true, path = "top" },
		{ map="-24,3", gather = true, path = "top" },
		{ map="-26,3", gather = true, path = "left" },
		{ map="-26,4", gather = true, path = "bottom" },
		{ map="-27,4", gather = true, path = "right" },
		{ map="-25,5", gather = true, path = "top" },
		{ map="-25,6", gather = true, path = "top" },
		{ map="-24,6", gather = true, path = "left" },
		{ map="-23,6", gather = true, path = "left" },
		{ map="-26,7", gather = true, path = "bottom" },
		{ map="-26,8", gather = true, path = "bottom" },
		{ map="-27,7", gather = true, path = "right" },
		{ map="-24,8", gather = true, path = "top" },
		{ map="-24,9", gather = true, path = "top" },
		{ map="-25,10", gather = true, path = "top" },
		{ map="-25,11", gather = true, path = "top" },
		{ map="-26,12", gather = true, path = "bottom" },
		{ map="-27,12", gather = true, path = "right" },
		{ map="-27,11", gather = true, path = "bottom" },
		{ map="-25,13", gather = true, path = "bottom" },
		{ map="-24,14", gather = true, path = "bottom" },
		{ map="-25,14", gather = true, path = "right" },
		{ map="-24,15", gather = true, path = "right" },
		{ map="-23,15", gather = true, path = "bottom" },
		{ map="-23,16", gather = true, path = "right" },
		{ map="-22,16", gather = true, path = "top" },
		{ map="-24,-5", path = "bottom" },
		{ map="-26,-4", path = "bottom" },
		{ map="-26,-1", path = "left" },
		{ map="-27,-1", path = "left" },
		{ map="-26,0", path = "right" },
		{ map="-27,3", path = "bottom" },
		{ map="-26,5", path = "bottom" },
		{ map="-26,6", path = "left" },
		{ map="-27,6", path = "bottom" },
		{ map="-26,9", path = "bottom" },
		{ map="-26,10", path = "bottom" },
		{ map="-26,13", path = "right" },
		{ map="-22,15", path = "top" },
		{ map="-22,14", path = "top" },
		{ map="-22,13", path = "left" },
		{ map="-23,13", path = "top" },
		{ map="-24,11", path = "left" },
		{ map="-25,9", path = "right" },
		{ map="-24,7", path = "right" },
		{ map="-23,7", path = "top" },
		{ map="-25,4", path = "top" },
		{ map="-25,3", path = "right" },
		{ map="-24,1", path = "top" },
		{ map="-24,-1", path = "right" },
		{ map="-24,-4", path = "left" },
		{ map="-26,-3", path = "left" },
		{ map="-26,11", path = "left" },
		{ map="-23,12", path = "left" },
		{ map="-24,12", gather = true, path = "top" },
		{ map="-23,-1", path = "top" },
		{ map="-20,-14", path = "bottom" },
		{ map="-20,-13", path = "left" },
		{ map="-21,-13", path = "left" },
		{ map="-22,-13", path = "left" },
		{ map="-23,-13", path = "bottom" },
		{ map="-23,-7", path = "bottom" },
		{ map="-23,-6", path = "bottom" },
		{ map="-23,-12", path = "bottom" },
		{ map="-23,-11", path = "bottom" },
		{ map="-23,-10", path = "bottom" },
		{ map="-23,-9", path = "bottom" },
		{ map="-23,-8", path = "bottom" },
	}
end

function Etape7()
	if msgetape7 == false then
		global:printMessage("Étape 7/8 ! Direction Pandala pour récolter du Bois de Bambou. (110 à 169)")
		msgetape7 = true
	end
	return {
		{ map="-20,-19", path = "top" },
		{ map="-20,-18", path = "top" },
		{ map="-20,-17", path = "top" },
		{ map="-20,-16", path = "top" },
		{ map="-20,-15", path = "top" },
		{ map="-23,-5", gather = true, path = "top" },
		{ map="-22,-5", gather = true, path = "left" },
		{ map="-22,-4", gather = true, path = "top" },
		{ map="-23,-4", gather = true, path = "right" },
		{ map="-23,-3", gather = true, path = "top" },
		{ map="-23,-2", gather = true, path = "left" },
		{ map="-24,-2", gather = true, path = "top" },
		{ map="-24,-3", gather = true, path = "right" },
		{ map="-25,-2", gather = true, path = "bottom" },
		{ map="-25,-4", gather = true, path = "top" },
		{ map="-25,-5", gather = true, path = "left" },
		{ map="-26,-5", gather = true, path = "bottom" },
		{ map="-27,-3", gather = true, path = "bottom" },
		{ map="-27,-2", gather = true, path = "right" },
		{ map="-26,-2", gather = true, path = "right" },
		{ map="-28,-1", gather = true, path = "bottom" },
		{ map="-28,0", gather = true, path = "right" },
		{ map="-27,0", gather = true, path = "right" },
		{ map="-25,-1", gather = true, path = "left" },
		{ map="-25,0", gather = true, path = "bottom" },
		{ map="-24,0", gather = true, path = "top" },
		{ map="-25,1", gather = true, path = "bottom" },
		{ map="-26,2", gather = true, path = "bottom" },
		{ map="-25,2", gather = true, path = "left" },
		{ map="-24,2", gather = true, path = "top" },
		{ map="-24,3", gather = true, path = "top" },
		{ map="-26,3", gather = true, path = "left" },
		{ map="-26,4", gather = true, path = "bottom" },
		{ map="-27,4", gather = true, path = "right" },
		{ map="-25,5", gather = true, path = "top" },
		{ map="-25,6", gather = true, path = "top" },
		{ map="-24,6", gather = true, path = "left" },
		{ map="-23,6", gather = true, path = "left" },
		{ map="-26,7", gather = true, path = "bottom" },
		{ map="-26,8", gather = true, path = "bottom" },
		{ map="-27,7", gather = true, path = "right" },
		{ map="-24,8", gather = true, path = "top" },
		{ map="-24,9", gather = true, path = "top" },
		{ map="-25,10", gather = true, path = "top" },
		{ map="-25,11", gather = true, path = "top" },
		{ map="-26,12", gather = true, path = "bottom" },
		{ map="-27,12", gather = true, path = "right" },
		{ map="-27,11", gather = true, path = "bottom" },
		{ map="-25,13", gather = true, path = "bottom" },
		{ map="-24,14", gather = true, path = "bottom" },
		{ map="-25,14", gather = true, path = "right" },
		{ map="-24,15", gather = true, path = "right" },
		{ map="-23,15", gather = true, path = "bottom" },
		{ map="-23,16", gather = true, path = "right" },
		{ map="-22,16", gather = true, path = "top" },
		{ map="-24,-5", path = "bottom" },
		{ map="-26,-4", path = "bottom" },
		{ map="-26,-1", path = "left" },
		{ map="-27,-1", path = "left" },
		{ map="-26,0", path = "right" },
		{ map="-27,3", path = "bottom" },
		{ map="-26,5", path = "bottom" },
		{ map="-26,6", path = "left" },
		{ map="-27,6", path = "bottom" },
		{ map="-26,9", path = "bottom" },
		{ map="-26,10", path = "bottom" },
		{ map="-26,13", path = "right" },
		{ map="-22,15", path = "top" },
		{ map="-22,14", path = "top" },
		{ map="-22,13", path = "left" },
		{ map="-23,13", path = "top" },
		{ map="-24,11", path = "left" },
		{ map="-25,9", path = "right" },
		{ map="-24,7", path = "right" },
		{ map="-23,7", path = "top" },
		{ map="-25,4", path = "top" },
		{ map="-25,3", path = "right" },
		{ map="-24,1", path = "top" },
		{ map="-24,-1", path = "right" },
		{ map="-24,-4", path = "left" },
		{ map="-26,-3", path = "left" },
		{ map="-26,11", path = "left" },
		{ map="-23,12", path = "left" },
		{ map="-24,12", gather = true, path = "top" },
		{ map="-23,-1", path = "top" },
		{ map="-20,-14", path = "top" },
		{ map="-20,-13", path = "top" },
		{ map="-21,-13", path = "right" },
		{ map="-22,-13", path = "right" },
		{ map="-23,-13", path = "right" },
		{ map="-23,-12", path = "top" },
		{ map="-23,-6", path = "top" },
		{ map="-23,-7", path = "top" },
		{ map="-23,-8", path = "top" },
		{ map="-23,-9", path = "top" },
		{ map="-23,-10", path = "top" },
		{ map="-23,-11", path = "top" },
		{ map="-20,-20", path = "right" },
		{ map="-19,-20", path = "right" },
		{ map="-18,-20", path = "right" },
		{ map="-17,-20", path = "right" },
		{ map="-16,-20", path = "right" },
		{ map="-15,-20", path = "right" },
		{ map="-13,-20", path = "right" },
		{ map="-12,-20", path = "right" },
		{ map="-14,-20", path = "right" },
		{ map="-11,-20", path = "right" },
		{ map="-10,-20", path = "right" },
		{ map="-9,-20", path = "right" },
		{ map="-8,-20", path = "right" },
		{ map="-7,-20", path = "right" },
		{ map="-6,-20", path = "right" },
		{ map="-5,-20", path = "right" },
		{ map="-4,-20", path = "right" },
		{ map="-3,-20", path = "right" },
		{ map="-2,-20", path = "right" },
		{ map="-1,-20", path = "right" },
		{ map="0,-20", path = "right" },
		{ map="1,-20", path = "right" },
		{ map="2,-20", path = "right" },
		{ map="3,-20", path = "right" },
		{ map="4,-20", path = "bottom" },

		{ map="4,-19", path = "right", custom = zaap7 },
		{ map="6,-19", path = "right" },
		{ map="5,-19", path = "right" },
		{ map="7,-19", path = "right" },
		{ map="8,-19", path = "right" },
		{ map="9,-19", path = "right" },
		{ map="10,-19", path = "top" },
		{ map="10,-20", path = "top" },
		{ map="10,-21", path = "right" },
		{ map="11,-21", path = "right" },
		{ map="12,-21", path = "right(111)" },
		{ map="16,-24", path = "right" },
		{ map="17,-26", path = "right" },
		{ map="19,-28", path = "right" },
		{ map="20,-28", gather = true, path = "bottom" },
		{ map="20,-27", gather = true, path = "bottom" },
		{ map="20,-26", gather = true, path = "bottom" },
		{ map="20,-25", gather = true, path = "bottom" },
		{ map="20,-23", gather = true, path = "bottom" },
		{ map="20,-22", gather = true, path = "left" },
		{ map="19,-22", gather = true, path = "bottom" },
		{ map="19,-21", gather = true, path = "right" },
		{ map="20,-21", gather = true, path = "right" },
		{ map="21,-21", gather = true, path = "top" },
		{ map="21,-22", gather = true, path = "right" },
		{ map="22,-22", gather = true, path = "bottom" },
		{ map="22,-21", gather = true, path = "bottom" },
		{ map="22,-20", gather = true, path = "right" },
		{ map="23,-21", gather = true, path = "right" },
		{ map="24,-21", gather = true, path = "right" },
		{ map="25,-22", gather = true, path = "top" },
		{ map="26,-24", gather = true, path = "top" },
		{ map="26,-25", gather = true, path = "right" },
		{ map="27,-25", gather = true, path = "top" },
		{ map="27,-26", gather = true, path = "left" },
		{ map="26,-26", gather = true, path = "left" },
		{ map="25,-26", gather = true, path = "left" },
		{ map="24,-26", gather = true, path = "top" },
		{ map="24,-27", gather = true, path = "right" },
		{ map="25,-27", gather = true, path = "right" },
		{ map="26,-27", gather = true, path = "right" },
		{ map="27,-27", gather = true, path = "top" },
		{ map="26,-28", gather = true, path = "left" },
		{ map="25,-28", gather = true, path = "left" },
		{ map="24,-28", gather = true, path = "left" },
		{ map="23,-28", gather = true, path = "left" },
		{ map="22,-28", gather = true, path = "left" },
		{ map="21,-28", gather = true, path = "top" },
		{ map="21,-29", gather = true, path = "right" },
		{ map="22,-29", gather = true, path = "right" },
		{ map="23,-29", gather = true, path = "right" },
		{ map="24,-29", gather = true, path = "right" },
		{ map="25,-29", gather = true, path = "right" },
		{ map="26,-29", gather = true, path = "right" },
		{ map="27,-29", gather = true, path = "top" },
		{ map="27,-30", gather = true, path = "left" },
		{ map="26,-30", gather = true, path = "top" },
		{ map="26,-31", gather = true, path = "right" },
		{ map="27,-31", gather = true, path = "top" },
		{ map="27,-32", gather = true, path = "right" },
		{ map="27,-33", gather = true, path = "left" },
		{ map="26,-33", gather = true, path = "top" },
		{ map="26,-34", gather = true, path = "right" },
		{ map="27,-34", gather = true, path = "right" },
		{ map="28,-33", gather = true, path = "left" },
		{ map="29,-33", gather = true, path = "left" },
		{ map="28,-32", gather = true, path = "right" },
		{ map="29,-32", gather = true, path = "top" },
		{ map="28,-34", gather = true, path = "top" },
		{ map="28,-35", gather = true, path = "left" },
		{ map="27,-35", gather = true, path = "top" },
		{ map="27,-36", gather = true, path = "right" },
		{ map="28,-36", gather = true, path = "top" },
		{ map="28,-37", gather = true, path = "left" },
		{ map="27,-37", gather = true, path = "left" },
		{ map="26,-37", path = "top", custom = zaap8 },
		{ map="26,-38", path = "right" },
		{ map="27,-38", gather = true, path = "top" },
		{ map="27,-39", gather = true, path = "top" },
		{ map="27,-40", path = "right" },
		{ map="28,-40", gather = true, path = "top" },
		{ map="28,-41", gather = true, path = "left" },
		{ map="27,-41", gather = true, path = "top(5)" },
		{ map="27,-42", gather = true, path = "top" },
		{ map="27,-43", gather = true, path = "left" },
		{ map="26,-43", gather = true, path = "left" },
		{ map="25,-43", gather = true, path = "bottom" },
		{ map="25,-42", gather = true, path = "left" },
		{ map="24,-42", gather = true, path = "left" },
		{ map="23,-42", gather = true, path = "bottom" },
		{ map="23,-41", gather = true, path = "left" },
		{ map="22,-41", gather = true, path = "bottom" },
		{ map="22,-40", gather = true, path = "left" },
		{ map="21,-39", gather = true, path = "left" },
		{ map="20,-39", gather = true, path = "bottom" },
		{ map="19,-38", gather = true, path = "left" },
		{ map="18,-38", gather = true, path = "bottom" },
		{ map="18,-37", gather = true, path = "left" },
		{ map="17,-37", gather = true, path = "bottom" },
		{ map="17,-36", gather = true, path = "right" },
		{ map="18,-36", gather = true, path = "right" },
		{ map="20,-36", gather = true, path = "bottom" },
		{ map="20,-35", gather = true, path = "bottom" },
		{ map="20,-34", gather = true, path = "bottom" },
		{ map="20,-33", gather = true, path = "bottom" },
		{ map="20,-32", gather = true, path = "bottom" },
		{ map="20,-31", gather = true, path = "right" },
		{ map="21,-31", gather = true, path = "bottom" },
		{ map="21,-30", gather = true, path = "left" },
		{ map="20,-30", path = "bottom" },
		{ map="20,-29", path = "bottom" },
		{ map="20,-24", path = "bottom" },
		{ map="23,-20", path = "top" },
		{ map="25,-21", path = "top" },
		{ map="25,-23", path = "right" },
		{ map="26,-23", path = "top" },
		{ map="27,-28", path = "left" },
		{ map="21,-40", path = "bottom" },
		{ map="20,-38", path = "left" },
		{ map="19,-36", path = "right" },
	}
end


function Etape8()
	if msgetape8 == false then
		global:printMessage("Étape 8/8 ! Direction Pandala pour récolter du Bois de Bombou Sombre.")
		msgetape8 = true
	end
	return {
		{ map="4,-19", path = "right" },
		{ map="6,-19", path = "right" },
		{ map="5,-19", path = "right" },
		{ map="7,-19", path = "right" },
		{ map="8,-19", path = "right" },
		{ map="9,-19", path = "right" },
		{ map="10,-19", path = "top" },
		{ map="10,-20", path = "top" },
		{ map="10,-21", path = "right" },
		{ map="11,-21", path = "right" },
		{ map="12,-21", path = "right(111)" },
		{ map="16,-24", path = "right" },
		{ map="17,-26", path = "right" },
		{ map="19,-28", path = "right" },
		{ map="20,-28", gather = true, path = "bottom" },
		{ map="20,-27", gather = true, path = "bottom" },
		{ map="20,-26", gather = true, path = "bottom" },
		{ map="20,-25", gather = true, path = "bottom" },
		{ map="20,-23", gather = true, path = "bottom" },
		{ map="20,-22", gather = true, path = "left" },
		{ map="19,-22", gather = true, path = "bottom" },
		{ map="19,-21", gather = true, path = "right" },
		{ map="20,-21", gather = true, path = "right" },
		{ map="21,-21", gather = true, path = "top" },
		{ map="21,-22", gather = true, path = "right" },
		{ map="22,-22", gather = true, path = "bottom" },
		{ map="22,-21", gather = true, path = "bottom" },
		{ map="22,-20", gather = true, path = "right" },
		{ map="23,-21", gather = true, path = "right" },
		{ map="24,-21", gather = true, path = "right" },
		{ map="25,-22", gather = true, path = "top" },
		{ map="26,-24", gather = true, path = "top" },
		{ map="26,-25", gather = true, path = "right" },
		{ map="27,-25", gather = true, path = "top" },
		{ map="27,-26", gather = true, path = "left" },
		{ map="26,-26", gather = true, path = "left" },
		{ map="25,-26", gather = true, path = "left" },
		{ map="24,-26", gather = true, path = "top" },
		{ map="24,-27", gather = true, path = "right" },
		{ map="25,-27", gather = true, path = "right" },
		{ map="26,-27", gather = true, path = "right" },
		{ map="27,-27", gather = true, path = "top" },
		{ map="26,-28", gather = true, path = "left" },
		{ map="25,-28", gather = true, path = "left" },
		{ map="24,-28", gather = true, path = "left" },
		{ map="23,-28", gather = true, path = "left" },
		{ map="22,-28", gather = true, path = "left" },
		{ map="21,-28", gather = true, path = "top" },
		{ map="21,-29", gather = true, path = "right" },
		{ map="22,-29", gather = true, path = "right" },
		{ map="23,-29", gather = true, path = "right" },
		{ map="24,-29", gather = true, path = "right" },
		{ map="25,-29", gather = true, path = "right" },
		{ map="26,-29", gather = true, path = "right" },
		{ map="27,-29", gather = true, path = "top" },
		{ map="27,-30", gather = true, path = "left" },
		{ map="26,-30", gather = true, path = "top" },
		{ map="26,-31", gather = true, path = "right" },
		{ map="27,-31", gather = true, path = "top" },
		{ map="27,-32", gather = true, path = "right" },
		{ map="27,-33", gather = true, path = "left" },
		{ map="26,-33", gather = true, path = "top" },
		{ map="26,-34", gather = true, path = "right" },
		{ map="27,-34", gather = true, path = "right" },
		{ map="28,-33", gather = true, path = "left" },
		{ map="29,-33", gather = true, path = "left" },
		{ map="28,-32", gather = true, path = "right" },
		{ map="29,-32", gather = true, path = "top" },
		{ map="28,-34", gather = true, path = "top" },
		{ map="28,-35", gather = true, path = "left" },
		{ map="27,-35", gather = true, path = "top" },
		{ map="27,-36", gather = true, path = "right" },
		{ map="28,-36", gather = true, path = "top" },
		{ map="28,-37", gather = true, path = "left" },
		{ map="27,-37", gather = true, path = "left" },
		{ map="26,-37", path = "top", custom = zaap8 },
		{ map="26,-38", path = "right" },
		{ map="27,-38", gather = true, path = "top" },
		{ map="27,-39", gather = true, path = "top" },
		{ map="27,-40", path = "right" },
		{ map="28,-40", gather = true, path = "top" },
		{ map="28,-41", gather = true, path = "left" },
		{ map="27,-41", gather = true, path = "top(5)" },
		{ map="27,-42", gather = true, path = "right" },
		{ map="27,-43", gather = true, path = "left" },
		{ map="26,-43", gather = true, path = "top" },
		{ map="25,-43", gather = true, path = "bottom" },
		{ map="25,-42", gather = true, path = "left" },
		{ map="24,-42", gather = true, path = "left" },
		{ map="23,-42", gather = true, path = "bottom" },
		{ map="23,-41", gather = true, path = "left" },
		{ map="22,-41", gather = true, path = "bottom" },
		{ map="22,-40", gather = true, path = "left" },
		{ map="21,-39", gather = true, path = "left" },
		{ map="20,-39", gather = true, path = "bottom" },
		{ map="19,-38", gather = true, path = "left" },
		{ map="18,-38", gather = true, path = "bottom" },
		{ map="18,-37", gather = true, path = "left" },
		{ map="17,-37", gather = true, path = "bottom" },
		{ map="17,-36", gather = true, path = "right" },
		{ map="18,-36", gather = true, path = "right" },
		{ map="20,-36", gather = true, path = "bottom" },
		{ map="20,-35", gather = true, path = "bottom" },
		{ map="20,-34", gather = true, path = "bottom" },
		{ map="20,-33", gather = true, path = "bottom" },
		{ map="20,-32", gather = true, path = "bottom" },
		{ map="20,-31", gather = true, path = "right" },
		{ map="21,-31", gather = true, path = "bottom" },
		{ map="21,-30", gather = true, path = "left" },
		{ map="20,-30", path = "bottom" },
		{ map="20,-29", path = "bottom" },
		{ map="20,-24", path = "bottom" },
		{ map="23,-20", path = "top" },
		{ map="25,-21", path = "top" },
		{ map="25,-23", path = "right" },
		{ map="26,-23", path = "top" },
		{ map="27,-28", path = "left" },
		{ map="21,-40", path = "bottom" },
		{ map="20,-38", path = "left" },
		{ map="19,-36", path = "right" },
		{ map="28,-47", gather = true, path = "bottom" },
		{ map="28,-46", gather = true, path = "bottom" },
		{ map="28,-45", gather = true, path = "left" },
		{ map="27,-45", gather = true, path = "bottom" },
		{ map="27,-44", gather = true, path = "bottom" },
		{ map="26,-45", gather = true, path = "left" },
		{ map="25,-45", gather = true, path = "bottom" },
		{ map="25,-44", gather = true, path = "bottom" },
		{ map="28,-42", path = "top(3)" },
		{ map="28,-43", path = "top" },
		{ map="28,-44", path = "right" },
		{ map="29,-44", path = "top" },
		{ map="29,-45", path = "top" },
		{ map="29,-46", path = "top" },
		{ map="29,-47", path = "left" },
		{ map="26,-44", path = "top" },
	}
end

-- function bank()
	-- return {
	
	-- }
-- end

function zaap1()
	if MyZaap ~= 1 then
		map:saveZaap()
		MyZaap = 1
		global:printSuccess("Sauvegarde du Zaap réalisée avec succès.")
	end
end

function zaap2()
	if MyZaap ~= 2 then
		map:saveZaap()
		MyZaap = 2
		global:printSuccess("Sauvegarde du Zaap réalisée avec succès.")
	end
end

function zaap3()
	if MyZaap ~= 3 then
		map:saveZaap()
		MyZaap = 3
		global:printSuccess("Sauvegarde du Zaap réalisée avec succès.")
	end
end
	
function zaap4()
	if MyZaap ~= 4 then
		map:saveZaap()
		MyZaap = 4
		global:printSuccess("Sauvegarde du Zaap réalisée avec succès.")
	end
end
	
function zaap5()
	if MyZaap ~= 5 then
		map:saveZaap()
		MyZaap = 5
		global:printSuccess("Sauvegarde du Zaap réalisée avec succès.")
	end
end
	
function zaap6()
	if MyZaap ~= 6 then
		map:saveZaap()
		MyZaap = 6
		global:printSuccess("Sauvegarde du Zaap réalisée avec succès.")
	end
end

function zaap7()
	if MyZaap ~= 7 then
		map:saveZaap()
		MyZaap = 7
		global:printSuccess("Sauvegarde du Zaap réalisée avec succès.")
	end
end