BANK_BONTA = true
BANK_ASTRUB = false
PLANNING = {7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22}

MAP_ACTUELLE = map:currentMap()
PODS_MAX = inventory:podsMax()
PODS = inventory:pods()
RATIO_PODS = (PODS / PODS_MAX) * 100
MAP_ID = map:currentMapId()

function getAllItems()
	exchange:getAllItems()
end

function getMapID()	
	printMessage(MAP_ID)
end

function CustomBank()

npc:npcBank(-1)
exchange:getAllItems()
global:leaveDialog()
map:moveToCell(424)
end

function House()
    map:lockedHouse(65,"58629277","milkoww")
end
function cleanInHouse()
	map:lockedStorage(333,"58629277")
	exchange:putAllItems()
	global:delay(1000)
    global:printSuccess("vidange faites")
	global:leaveDialog()
	map:moveToCell(483)
end

function exitHouse()
	map:moveToCell(483)
end
 
OPEN_BAGS = true
OPEN_BAGS = true

function changegather()
    if job:level(36) <= 200 then
        GATHER = { 75, 71, 74, 77, 76, 78, 79, 81 }
    end
end

function move()
    changegather()
	return {
		{map = "2883855", custom = exitHouse},
		{ map = "-31,-58", path = "havenbag" },
		{map = "0,0", path =  "zaap(84674563)"},



		{ map = "4,-19", path = "bottom" },
		{ map = "4,-18", path = "bottom" },
		{ map = "4,-17", path = "left" },
		{ map = "3,-17", path = "left" },
		{ map = "2,-17", gather = true, path = "left" },
		{ map = "1,-17", gather = true, path = "left" },
		{ map = "0,-17", gather = true, path = "top" },
		{ map = "0,-18", gather = true, path = "right" },
		{ map = "1,-18", gather = true, path = "right" },
		{ map = "2,-18", gather = true, path = "top" },
		{ map = "2,-19", path = "top" },
		{ map = "2,-20", path = "left" },
		{ map = "1,-20", path = "left" },
		{ map = "0,-20", path = "left" },
		{ map = "-1,-20", path = "left" },
		{ map = "-2,-20", path = "top" },
		{ map = "-2,-22", path = "top" },
		{ map = "-2,-21", path = "top" },
		{ map = "-2,-23", path = "top" },
		{ map = "-2,-24", path = "top" },
		{ map = "-2,-25", path = "right" },
		{ map = "-1,-25", path = "right" },
		{ map = "0,-25", path = "top" },
		{ map = "0,-26", path = "top" },
		{ map = "0,-27", gather = true, path = "right" },
		{ map = "1,-27", path = "top" },
		{ map = "1,-28", gather = true, path = "right" },
		{ map = "2,-28", gather = true, path = "top" },
		{ map = "2,-29", gather = true, path = "right" },
		{ map = "3,-29", path = "bottom" },
		{ map = "3,-28", path = "bottom" },
		{ map = "3,-27", path = "bottom" },
		{ map = "3,-26", path = "bottom" },
		{ map = "3,-25", path = "right" },
		{ map = "4,-25", path = "right" },
		{ map = "5,-25", path = "right" },
		{ map = "6,-25", path = "right" },
		{ map = "7,-25", path = "right" },
		{ map = "8,-25", path = "right" },
		{ map = "9,-25", path = "right" },
		{ map = "10,-25", path = "right" },
		{ map = "11,-25", gather = true, path = "top" },
		{ map = "11,-26", path = "left" },
		{ map = "10,-26", gather = true, path = "top" },
		{ map = "10,-27", path = "left" },
		{ map = "9,-27", path = "left" },
		{ map = "8,-27", gather = true, path = "top" },
		{ map = "8,-28", path = "top" },
		{ map = "8,-29", gather = true, path = "right" },
		{ map = "9,-29", gather = true, path = "right" },
		{ map = "10,-29", gather = true, path = "bottom" },
		{ map = "10,-28", path = "right" },
		{ map = "11,-28", gather = true, path = "right" },
		{ map = "12,-28", path = "bottom" },
		{ map = "12,-27", gather = true, path = "bottom" },
		{ map = "12,-26", gather = true, path = "bottom" },
		{ map = "12,-25", path = "bottom" },
		{ map = "12,-24", gather = true, path = "bottom" },
		{ map = "12,-23", path = "bottom" },
		{ map = "12,-22", path = "bottom" },
		{ map = "12,-21", gather = true, path = "bottom" },
		{ map = "12,-20", gather = true, path = "bottom" },
		{ map = "12,-19", gather = true, path = "bottom" },
		{ map = "12,-18", gather = true, path = "bottom" },
		{ map = "12,-17", path = "bottom" },
		{ map = "12,-16", gather = true, path = "bottom" },
		{ map = "12,-15", gather = true, path = "left" },
		{ map = "11,-15", path = "bottom" },
		{ map = "11,-14", gather = true, path = "bottom" },
		{ map = "11,-13", gather = true, path = "bottom" },
		{ map = "11,-12", gather = true, path = "bottom" },
		{ map = "11,-11", path = "left" },
		{ map = "10,-11", path = "bottom" },
		{ map = "10,-10", gather = true, path = "left" },
		{ map = "9,-10", path = "bottom" },
		{ map = "9,-9", gather = true, path = "left" },
		{ map = "8,-9", path = "left" },
		{ map = "8,-8", gather = true, path = "left" },
		{ map = "7,-8", path = "top" },
		{ map = "7,-9", path = "left" },
		{ map = "6,-9", gather = true, path = "left" },
		{ map = "5,-9", gather = true, path = "left" },
		{ map = "4,-9", path = "bottom(558)" },
		{ map = "4,-8", path = "bottom" },
		{ map = "4,-7", path = "bottom" },
		{ map = "4,-6", path = "right" },
		{ map = "5,-6", path = "right" },
		{ map = "6,-6", path = "right" },
		{ map = "7,-6", gather = true, path = "right" },
		{ map = "8,-6", path = "bottom" },
		{ map = "8,-5", gather = true, path = "left" },
		{ map = "7,-5", gather = true, path = "bottom" },
		{ map = "7,-4", gather = true, path = "left" },
		{ map = "6,-4", gather = true, path = "bottom" },
		{ map = "6,-3", gather = true, path = "left" },
		{ map = "5,-3", gather = true, path = "bottom" },
		{ map = "5,-2", gather = true, path = "bottom" },
		{ map = "5,-1", gather = true, path = "right" },
		{ map = "6,-1", gather = true, path = "right" },
		{ map = "7,-1", gather = true, path = "bottom" },
		{ map = "7,0", gather = true, path = "right" },
		{ map = "8,0", gather = true, path = "bottom" },
		{ map = "8,1", gather = true, path = "right" },
		{ map = "9,1", gather = true, path = "right" },
		{ map = "10,1", gather = true, path = "bottom(548)" },
		{ map = "10,2", gather = true, path = "bottom" },
		{ map = "10,3", gather = true, path = "right" },
		{ map = "11,3", gather = true, path = "right" },
		{ map = "12,3", gather = true, path = "bottom" },
		{ map = "12,4", path = "right" },
		{ map = "13,4", gather = true, path = "bottom" },
		{ map = "13,5", gather = true, path = "bottom" },
		{ map = "13,6", gather = true, path = "left" },
		{ map = "12,6", gather = true, path = "bottom" },
		{ map = "12,7", path = "right" },
		{ map = "13,7", gather = true, path = "bottom" },
		{ map = "13,8", gather = true, path = "left" },
		{ map = "12,8", path = "left" },
		{ map = "11,8", gather = true, path = "bottom" },
		{ map = "11,9", path = "bottom" },
		{ map = "11,10", path = "right" },
		{ map = "12,10", gather = true, path = "bottom" },
		{ map = "12,11", path = "bottom" },
		{ map = "12,12", gather = true, path = "right" },
		{ map = "13,12", gather = true, path = "bottom" },
		{ map = "13,13", gather = true, path = "left" },
		{ map = "12,13", gather = true, path = "bottom" },
		{ map = "12,14", gather = true, path = "bottom" },
		{ map = "12,15", gather = true, path = "right" },
		{ map = "13,15", gather = true, path = "bottom" },
		{ map = "13,16", gather = true, path = "bottom" },
		{ map = "13,17", gather = true, path = "bottom" },
		{ map = "13,18", gather = true, path = "left" },
		{ map = "12,18", gather = true, path = "bottom" },
		{ map = "12,19", gather = true, path = "bottom" },
		{ map = "12,20", gather = true, path = "bottom" },
		{ map = "12,21", path = "bottom" },
		{ map = "12,22", gather = true, path = "right" },
		{ map = "13,22", gather = true, path = "right" },
		{ map = "14,22", path = "right(307)" },
		{ map = "15,22", gather = true, path = "right(335)" },
		{ map = "16,22", path = "bottom(452)" },
		{ map = "16,23", gather = true, path = "left(280)" },
		{ map = "15,23", path = "bottom(549)" },
		{ map = "15,24", path = "right(279" },
		{ map = "16,24", gather = true, path = "right(335)" },
		{ map = "17,24", gather = true, path = "bottom(554)" },
		{ map = "18,24", gather = true, path = "right(335)" },
		{ map = "19,24", gather = true, path = "right(195)" },
		{ map = "20,24", gather = true, path = "bottom(460)" },
		{ map = "20,25", gather = true, path = "left(308)" },
		{ map = "19,25", gather = true, path = "left(308)" },
		{ map = "18,25", path = "left(224)" },
		{ map = "17,25", path = "bottom(552)" },
		{ map = "17,26", gather = true, path = "left(168)" },
		{ map = "16,26", gather = true, path = "left(308)" },
		{ map = "15,26", gather = true, path = "left(280)" },
		{ map = "14,26", gather = true, path = "left(280)" },
		{ map = "13,26", gather = true, path = "left(252)" },
		{ map = "12,26", gather = true, path = "left(504)" },
		{ map = "11,26", path = "bottom(554)" },
		{ map = "11,27", gather = true, path = "right(195)" },
		{ map = "12,27", path = "right(279)" },
		{ map = "13,27", gather = true, path = "bottom(540)" },
		{ map = "13,28", gather = true, path = "right(391)" },
		{ map = "14,28", gather = true, path = "bottom(551)" },
		{ map = "14,29", path = "left(364)" },
		{ map = "13,29", gather = true, path = "left(280)" },
		{ map = "12,29", gather = true, path = "left(168)" },
		{ map = "11,29", path = "top" },
		{ map = "11,28", gather = true, path = "left" },
		{ map = "10,28", path = "left" },
		{ map = "9,28", gather = true, path = "bottom" },
		{ map = "9,29", gather = true, path = "left" },
		{ map = "8,29", gather = true, path = "bottom" },
		{ map = "8,30", path = "bottom" },
		{ map = "8,31", gather = true, path = "left" },
		{ map = "7,31", gather = true, path = "left" },
		{ map = "6,31", gather = true, path = "left" },
		{ map = "5,31", gather = true, path = "bottom" },
		{ map = "5,32", gather = true, path = "left" },
		{ map = "4,32", gather = true, path = "left" },
		{ map = "3,32", gather = true, path = "left" },
		{ map = "2,32", gather = true, path = "top" },
		{ map = "2,31", path = "top" },
		{ map = "2,30", path = "left" },
		{ map = "1,30", path = "left" },
		{ map = "0,30", gather = true, path = "top" },
		{ map = "0,29", gather = true, path = "top" },
		{ map = "0,28", gather = true, path = "right" },
		{ map = "1,28", path = "right" },
		{ map = "2,28", path = "top" },
		{ map = "2,27", gather = true, path = "left" },
		{ map = "1,27", path = "left" },
		{ map = "0,27", gather = true, path = "top" },
		{ map = "0,26", gather = true, path = "top" },
		{ map = "0,25", gather = true, path = "top" },
		{ map = "0,24", gather = true, path = "left" },
		{ map = "-1,24", gather = true, path = "left" },
		{ map = "-2,24", path = "top" },
		{ map = "-2,23", gather = true, path = "top" },
		{ map = "-2,22", gather = true, path = "right" },
		{ map = "-1,22", gather = true, path = "bottom" },
		{ map = "-1,23", gather = true, path = "right" },
		{ map = "0,23", path = "right" },
		{ map = "1,23", path = "right" },
		{ map = "2,23", path = "top" },
		{ map = "2,22", gather = true, path = "right" },
		{ map = "3,22", path = "bottom" },
		{ map = "3,23", path = "bottom" },
		{ map = "3,24", path = "right" },
		{ map = "4,24", gather = true, path = "top" },
		{ map = "4,23", path = "right" },
		{ map = "5,23", gather = true, path = "right" },
		{ map = "6,23", gather = true, path = "right" },
		{ map = "7,23", gather = true, path = "top" },
		{ map = "7,22", gather = true, path = "top" },
		{ map = "7,21", path = "right" },
		{ map = "8,21", gather = true, path = "right" },
		{ map = "9,21", path = "bottom" },
		{ map = "9,22", gather = true, path = "right" },
		{ map = "10,22", gather = true, path = "right" },
		{ map = "11,22", path = "top" },
		{ map = "11,21", path = "top" },
		{ map = "11,19", gather = true, path = "left" },
		{ map = "11,20", gather = true, path = "top" },
		{ map = "10,19", gather = true, path = "left" },
		{ map = "9,19", gather = true, path = "left" },
		{ map = "8,19", gather = true, path = "top" },
		{ map = "8,18", gather = true, path = "left" },
		{ map = "7,18", gather = true, path = "top" },
		{ map = "7,17", gather = true, path = "top" },
		{ map = "7,16", gather = true, path = "top" },
		{ map = "7,15", gather = true, path = "top" },
		{ map = "7,14", gather = true, path = "right" },
		{ map = "8,14", gather = true, path = "top" },
		{ map = "8,13", gather = true, path = "right" },
		{ map = "9,13", gather = true, path = "top" },
		{ map = "9,12", gather = true, path = "top" },
		{ map = "9,11", path = "left" },
		{ map = "8,11", path = "left" },
		{ map = "7,11", path = "left" },
		{ map = "6,11", path = "left" },
		{ map = "5,11", path = "left" },
		{ map = "4,11", path = "top" },
		{ map = "4,10", path = "top" },
		{ map = "4,9", path = "top" },
		{ map = "4,8", path = "top" },
		{ map = "4,7", path = "top" },
		{ map = "4,6", path = "top" },
		{ map = "4,5", path = "top" },
		{ map = "4,4", path = "top" },
		{ map = "4,3", path = "top" },
		{ map = "4,2", path = "top" },
		{ map = "4,1", path = "top" },
		{ map = "4,-1", path = "left" },
		{ map = "4,0", path = "top" },
		{ map = "3,-1", path = "top" },
		{ map = "3,-2", gather = true, path = "left" },
		{ map = "2,-2", path = "top" },
		{ map = "2,-3", gather = true, path = "left" },
		{ map = "1,-3", path = "top" },
		{ map = "1,-4", gather = true, path = "top" },
		{ map = "1,-5", path = "top" },
		{ map = "1,-6", path = "top" },
		{ map = "1,-7", path = "top" },
		{ map = "1,-8", path = "right" },
		{ map = "2,-8", gather = true, path = "right" },
		{ map = "3,-8", gather = true, path = "top" },
		{ map = "3,-9", path = "top" },
		{ map = "3,-10", path = "top" },
		{ map = "3,-11", path = "top" },
		{ map = "3,-12", path = "top" },
		{ map = "3,-13", path = "right" },
		{ map = "4,-13", path = "top" },
		{ map = "4,-14", path = "top" },
		{ map = "4,-15", path = "top" },
		{ map = "84674566", path = "top" },
		{ map = "83887104", path = "396" },
	}
end

function bank()
	return {
		{ map = "4,-19", path = "bottom" },
		{ map = "4,-18", path = "bottom" },
		{ map = "4,-17", path = "bottom" },
		{ map = "3,-17", path = "havenbag" },
		{ map = "2,-17", path = "havenbag" },
		{ map = "1,-17", path = "havenbag" },
		{ map = "0,-17", path = "havenbag" },
		{ map = "0,-18", path = "havenbag" },
		{ map = "1,-18", path = "havenbag" },
		{ map = "2,-18", path = "havenbag" },
		{ map = "2,-19", path = "havenbag" },
		{ map = "2,-20", path = "havenbag" },
		{ map = "1,-20", path = "havenbag" },
		{ map = "0,-20", path = "havenbag" },
		{ map = "-1,-20", path = "havenbag" },
		{ map = "-2,-20", path = "havenbag" },
		{ map = "-2,-22", path = "havenbag" },
		{ map = "-2,-21", path = "havenbag" },
		{ map = "-2,-23", path = "havenbag" },
		{ map = "-2,-24", path = "havenbag" },
		{ map = "-2,-25", path = "havenbag" },
		{ map = "-1,-25", path = "havenbag" },
		{ map = "0,-25", path = "havenbag" },
		{ map = "0,-26", path = "havenbag" },
		{ map = "0,-27", path = "havenbag" },
		{ map = "1,-27", path = "havenbag" },
		{ map = "1,-28", path = "havenbag" },
		{ map = "2,-28", path = "havenbag" },
		{ map = "2,-29", path = "havenbag" },
		{ map = "3,-29", path = "havenbag" },
		{ map = "3,-28", path = "havenbag" },
		{ map = "3,-27", path = "havenbag" },
		{ map = "3,-26", path = "havenbag" },
		{ map = "3,-25", path = "havenbag" },
		{ map = "4,-25", path = "havenbag" },
		{ map = "5,-25", path = "havenbag" },
		{ map = "6,-25", path = "havenbag" },
		{ map = "7,-25", path = "havenbag" },
		{ map = "8,-25", path = "havenbag" },
		{ map = "9,-25", path = "havenbag" },
		{ map = "10,-25", path = "havenbag" },
		{ map = "11,-25", path = "havenbag" },
		{ map = "11,-26", path = "havenbag" },
		{ map = "10,-26", path = "havenbag" },
		{ map = "10,-27", path = "havenbag" },
		{ map = "9,-27", path = "havenbag" },
		{ map = "8,-27", path = "havenbag" },
		{ map = "8,-28", path = "havenbag" },
		{ map = "8,-29", path = "havenbag" },
		{ map = "9,-29", path = "havenbag" },
		{ map = "10,-29", path = "havenbag" },
		{ map = "10,-28", path = "havenbag" },
		{ map = "11,-28", path = "havenbag" },
		{ map = "12,-28", path = "havenbag" },
		{ map = "12,-27", path = "havenbag" },
		{ map = "12,-26", path = "havenbag" },
		{ map = "12,-25", path = "havenbag" },
		{ map = "12,-24", path = "havenbag" },
		{ map = "12,-23", path = "havenbag" },
		{ map = "12,-22", path = "havenbag" },
		{ map = "12,-21", path = "havenbag" },
		{ map = "12,-20", path = "havenbag" },
		{ map = "12,-19", path = "havenbag" },
		{ map = "12,-18", path = "havenbag" },
		{ map = "12,-17", path = "havenbag" },
		{ map = "12,-16", path = "havenbag" },
		{ map = "12,-15", path = "havenbag" },
		{ map = "11,-15", path = "havenbag" },
		{ map = "11,-14", path = "havenbag" },
		{ map = "11,-13", path = "havenbag" },
		{ map = "11,-12", path = "havenbag" },
		{ map = "11,-11", path = "havenbag" },
		{ map = "10,-11", path = "havenbag" },
		{ map = "10,-10", path = "havenbag" },
		{ map = "9,-10", path = "havenbag" },
		{ map = "9,-9", path = "havenbag" },
		{ map = "8,-9", path = "havenbag" },
		{ map = "8,-8", path = "havenbag" },
		{ map = "7,-8", path = "havenbag" },
		{ map = "7,-9", path = "havenbag" },
		{ map = "6,-9", path = "havenbag" },
		{ map = "5,-9", path = "havenbag" },
		{ map = "4,-9", path = "havenbag" },
		{ map = "4,-8", path = "havenbag" },
		{ map = "4,-7", path = "havenbag" },
		{ map = "4,-6", path = "havenbag" },
		{ map = "5,-6", path = "havenbag" },
		{ map = "6,-6", path = "havenbag" },
		{ map = "7,-6", path = "havenbag" },
		{ map = "8,-6", path = "havenbag" },
		{ map = "8,-5", path = "havenbag" },
		{ map = "7,-5", path = "havenbag" },
		{ map = "7,-4", path = "havenbag" },
		{ map = "6,-4", path = "havenbag" },
		{ map = "6,-3", path = "havenbag" },
		{ map = "5,-3", path = "havenbag" },
		{ map = "5,-2", path = "havenbag" },
		{ map = "5,-1", path = "havenbag" },
		{ map = "6,-1", path = "havenbag" },
		{ map = "7,-1", path = "havenbag" },
		{ map = "7,0", path = "havenbag" },
		{ map = "8,0", path = "havenbag" },
		{ map = "8,1", path = "havenbag" },
		{ map = "9,1", path = "havenbag" },
		{ map = "10,1", path = "havenbag" },
		{ map = "10,2", path = "havenbag" },
		{ map = "10,3", path = "havenbag" },
		{ map = "11,3", path = "havenbag" },
		{ map = "12,3", path = "havenbag" },
		{ map = "12,4", path = "havenbag" },
		{ map = "13,4", path = "havenbag" },
		{ map = "13,5", path = "havenbag" },
		{ map = "13,6", path = "havenbag" },
		{ map = "12,6", path = "havenbag" },
		{ map = "12,7", path = "havenbag" },
		{ map = "13,7", path = "havenbag" },
		{ map = "13,8", path = "havenbag" },
		{ map = "12,8", path = "havenbag" },
		{ map = "11,8", path = "havenbag" },
		{ map = "11,9", path = "havenbag" },
		{ map = "11,10", path = "havenbag" },
		{ map = "12,10", path = "havenbag" },
		{ map = "12,11", path = "havenbag" },
		{ map = "12,12", path = "havenbag" },
		{ map = "12,13", path = "havenbag" },
		{ map = "12,14", path = "havenbag" },
		{ map = "12,15", path = "havenbag" },
		{ map = "13,15", path = "havenbag" },
		{ map = "13,16", path = "havenbag" },
		{ map = "13,17", path = "havenbag" },
		{ map = "13,18", path = "havenbag" },
		{ map = "12,18", path = "havenbag" },
		{ map = "12,19", path = "havenbag" },
		{ map = "12,20", path = "havenbag" },
		{ map = "12,21", path = "havenbag" },
		{ map = "12,22", path = "havenbag" },
		{ map = "13,22", path = "havenbag" },
		{ map = "14,22", path = "havenbag" },
		{ map = "15,22", path = "havenbag" },
		{ map = "16,22", path = "havenbag" },
		{ map = "16,23", path = "havenbag" },
		{ map = "15,23", path = "havenbag" },
		{ map = "15,24", path = "havenbag" },
		{ map = "16,24", path = "havenbag" },
		{ map = "17,24", path = "havenbag" },
		{ map = "18,24", path = "havenbag" },
		{ map = "19,24", path = "havenbag" },
		{ map = "20,24", path = "havenbag" },
		{ map = "20,25", path = "havenbag" },
		{ map = "19,25", path = "havenbag" },
		{ map = "18,25", path = "havenbag" },
		{ map = "17,25", path = "havenbag" },
		{ map = "17,26", path = "havenbag" },
		{ map = "16,26", path = "havenbag" },
		{ map = "15,26", path = "havenbag" },
		{ map = "14,26", path = "havenbag" },
		{ map = "13,26", path = "havenbag" },
		{ map = "12,26", path = "havenbag" },
		{ map = "11,26", path = "havenbag" },
		{ map = "11,27", path = "havenbag" },
		{ map = "12,27", path = "havenbag" },
		{ map = "13,27", path = "havenbag" },
		{ map = "13,28", path = "havenbag" },
		{ map = "14,28", path = "havenbag" },
		{ map = "14,29", path = "havenbag" },
		{ map = "13,29", path = "havenbag" },
		{ map = "12,29", path = "havenbag" },
		{ map = "11,29", path = "havenbag" },
		{ map = "11,28", path = "havenbag" },
		{ map = "10,28", path = "havenbag" },
		{ map = "9,28", path = "havenbag" },
		{ map = "9,29", path = "havenbag" },
		{ map = "8,29", path = "havenbag" },
		{ map = "8,30", path = "havenbag" },
		{ map = "8,31", path = "havenbag" },
		{ map = "7,31", path = "havenbag" },
		{ map = "6,31", path = "havenbag" },
		{ map = "5,31", path = "havenbag" },
		{ map = "5,32", path = "havenbag" },
		{ map = "4,32", path = "havenbag" },
		{ map = "3,32", path = "havenbag" },
		{ map = "2,32", path = "havenbag" },
		{ map = "2,31", path = "havenbag" },
		{ map = "2,30", path = "havenbag" },
		{ map = "1,30", path = "havenbag" },
		{ map = "0,30", path = "havenbag" },
		{ map = "0,29", path = "havenbag" },
		{ map = "0,28", path = "havenbag" },
		{ map = "1,28", path = "havenbag" },
		{ map = "2,28", path = "havenbag" },
		{ map = "2,27", path = "havenbag" },
		{ map = "1,27", path = "havenbag" },
		{ map = "0,27", path = "havenbag" },
		{ map = "0,26", path = "havenbag" },
		{ map = "0,25", path = "havenbag" },
		{ map = "0,24", path = "havenbag" },
		{ map = "-1,24", path = "havenbag" },
		{ map = "-2,24", path = "havenbag" },
		{ map = "-2,23", path = "havenbag" },
		{ map = "-2,22", path = "havenbag" },
		{ map = "-1,22", path = "havenbag" },
		{ map = "-1,23", path = "havenbag" },
		{ map = "0,23", path = "havenbag" },
		{ map = "1,23", path = "havenbag" },
		{ map = "2,23", path = "havenbag" },
		{ map = "2,22", path = "havenbag" },
		{ map = "3,22", path = "havenbag" },
		{ map = "3,23", path = "havenbag" },
		{ map = "3,24", path = "havenbag" },
		{ map = "4,24", path = "havenbag" },
		{ map = "4,23", path = "havenbag" },
		{ map = "5,23", path = "havenbag" },
		{ map = "6,23", path = "havenbag" },
		{ map = "7,23", path = "havenbag" },
		{ map = "7,22", path = "havenbag" },
		{ map = "7,21", path = "havenbag" },
		{ map = "8,21", path = "havenbag" },
		{ map = "9,21", path = "havenbag" },
		{ map = "9,22", path = "havenbag" },
		{ map = "10,22", path = "havenbag" },
		{ map = "11,22", path = "havenbag" },
		{ map = "11,21", path = "havenbag" },
		{ map = "11,19", path = "havenbag" },
		{ map = "11,20", path = "havenbag" },
		{ map = "10,19", path = "havenbag" },
		{ map = "9,19", path = "havenbag" },
		{ map = "8,19", path = "havenbag" },
		{ map = "8,18", path = "havenbag" },
		{ map = "7,18", path = "havenbag" },
		{ map = "7,17", path = "havenbag" },
		{ map = "7,16", path = "havenbag" },
		{ map = "7,15", path = "havenbag" },
		{ map = "7,14", path = "havenbag" },
		{ map = "8,14", path = "havenbag" },
		{ map = "8,13", path = "havenbag" },
		{ map = "9,13", path = "havenbag" },
		{ map = "9,12", path = "havenbag" },
		{ map = "9,11", path = "havenbag" },
		{ map = "8,11", path = "havenbag" },
		{ map = "7,11", path = "havenbag" },
		{ map = "6,11", path = "havenbag" },
		{ map = "5,11", path = "havenbag" },
		{ map = "4,11", path = "havenbag" },
		{ map = "4,10", path = "havenbag" },
		{ map = "4,9", path = "havenbag" },
		{ map = "4,8", path = "havenbag" },
		{ map = "4,7", path = "havenbag" },
		{ map = "4,6", path = "havenbag" },
		{ map = "4,5", path = "havenbag" },
		{ map = "4,4", path = "havenbag" },
		{ map = "4,3", path = "havenbag" },
		{ map = "4,2", path = "havenbag" },
		{ map = "4,1", path = "havenbag" },
		{ map = "4,-1", path = "havenbag" },
		{ map = "4,0", path = "havenbag" },
		{ map = "3,-1", path = "havenbag" },
		{ map = "3,-2", path = "havenbag" },
		{ map = "2,-2", path = "havenbag" },
		{ map = "2,-3", path = "havenbag" },
		{ map = "1,-3", path = "havenbag" },
		{ map = "1,-4", path = "havenbag" },
		{ map = "1,-5", path = "havenbag" },
		{ map = "1,-6", path = "havenbag" },
		{ map = "1,-7", path = "havenbag" },
		{ map = "1,-8", path = "havenbag" },
		{ map = "2,-8", path = "havenbag" },
		{ map = "3,-8", path = "havenbag" },
		{ map = "3,-9", path = "havenbag" },
		{ map = "3,-10", path = "havenbag" },
		{ map = "3,-11", path = "havenbag" },
		{ map = "3,-12", path = "havenbag" },
		{ map = "3,-13", path = "havenbag" },
		{ map = "4,-13", path = "havenbag" },
		{ map = "4,-14", path = "havenbag" },
		{ map = "4,-15", path = "havenbag" },
		{map = "0,0", path =  "zaap(147768)"},
	   	--commence banque bonta
	   	{map = "-32,-56", path = "top"},
	  	{map = "-32,-57", path = "top"},
	  	{map = "-32,-58", path = "right"},

      	{ map = "147258", custom = House },
      	{map = "2883855", custom = cleanInHouse}
	}
end